// Generated by CoffeeScript 2.7.0
(function() {
  // Storage Manager using electron-store
  // Integrates with existing classes (Settings, Bot, Session, etc.)
  var StorageManager, Store, path;

  Store = require('electron-store');

  path = require('path');

  StorageManager = (function() {
    class StorageManager {
      static getInstance() {
        return this.instance != null ? this.instance : this.instance = new StorageManager();
      }

      constructor() {
        this.store = new Store({
          name: 'coffeeclaw-data',
          cwd: path.join(path.dirname(__dirname), '.secrete'),
          defaults: {
            settings: null,
            bots: null,
            sessions: null,
            license: null,
            agentSessions: null
          }
        });
        this._cache = new Map();
        this._dirty = new Set();
      }

      get(key) {
        var data;
        if (this._cache.has(key)) {
          return this._cache.get(key);
        }
        data = this.store.get(key);
        this._cache.set(key, data);
        return data;
      }

      set(key, value) {
        this._cache.set(key, value);
        this._dirty.add(key);
        return this;
      }

      save(key) {
        var data;
        if (!this._dirty.has(key)) {
          return this;
        }
        data = this._cache.get(key);
        if (data != null ? data.toJSON : void 0) {
          this.store.set(key, data.toJSON());
        } else {
          this.store.set(key, data);
        }
        this._dirty.delete(key);
        this.emit('saved', key);
        return this;
      }

      saveAll() {
        var key, ref;
        ref = this._dirty;
        for (key of ref) {
          this.save(key);
        }
        return this;
      }

      delete(key) {
        this._cache.delete(key);
        this._dirty.delete(key);
        this.store.delete(key);
        return this;
      }

      clear() {
        this._cache.clear();
        this._dirty.clear();
        this.store.clear();
        return this;
      }

      has(key) {
        return this.store.has(key) || this._cache.has(key);
      }

      getPath() {
        return this.store.path;
      }

    };

    StorageManager.instance = null;

    return StorageManager;

  }).call(this);

  module.exports = {StorageManager};

}).call(this);
