// Generated by CoffeeScript 2.7.0
(function() {
  // Typed Storage - integrates electron-store with existing classes
  var Bot, License, Model, Session, SessionManager, Settings, StorageManager, TypedStorage;

  ({StorageManager} = require('./storage'));

  ({Settings} = require('../settings'));

  ({Bot} = require('../bot'));

  ({Session, SessionManager} = require('../session'));

  ({License} = require('../license'));

  ({Model} = require('../model'));

  TypedStorage = (function() {
    class TypedStorage {
      static getInstance() {
        return this.instance != null ? this.instance : this.instance = new TypedStorage();
      }

      constructor() {
        this.storage = StorageManager.getInstance();
        this._cache = {};
      }

      
        // Settings
      getSettings() {
        var data;
        if (this._cache.settings) {
          return this._cache.settings;
        }
        data = this.storage.get('settings');
        if ((data != null ? data.__class : void 0) === 'Settings') {
          this._cache.settings = Settings.fromJSON(data);
        } else if (data) {
          this._cache.settings = Settings.fromLegacy(data);
        } else {
          this._cache.settings = new Settings();
        }
        return this._cache.settings;
      }

      saveSettings(settings = null) {
        this._cache.settings = settings != null ? settings : this._cache.settings;
        this.storage.set('settings', this._cache.settings);
        this.storage.save('settings');
        return this;
      }

      
        // Bots
      getBots() {
        var data, defaultBot, ref, ref1;
        if (this._cache.bots) {
          return this._cache.bots;
        }
        data = this.storage.get('bots');
        if ((data != null ? (ref = data.bots) != null ? (ref1 = ref[0]) != null ? ref1.__class : void 0 : void 0 : void 0) === 'Bot') {
          this._cache.bots = {
            bots: data.bots.map(function(b) {
              return Bot.fromJSON(b);
            }),
            activeBotId: data.activeBotId
          };
        } else if (data) {
          this._cache.bots = this._migrateBots(data);
        } else {
          defaultBot = Bot.createDefaultBot();
          this._cache.bots = {
            bots: [defaultBot],
            activeBotId: defaultBot.id
          };
        }
        return this._cache.bots;
      }

      _migrateBots(data) {
        var activeBotId, bot, botData, bots, defaultBot, e, i, len, model, ref, ref1, ref2, ref3;
        bots = [];
        activeBotId = data != null ? data.activeBotId : void 0;
        if ((data != null ? data.bots : void 0) && Array.isArray(data.bots)) {
          ref = data.bots;
          for (i = 0, len = ref.length; i < len; i++) {
            botData = ref[i];
            try {
              model = Model.create((ref1 = botData.model) != null ? ref1 : 'glm-4-flash', 'zhipu');
              bot = new Bot(botData.id, botData.name, botData.description, model, botData.systemPrompt, (ref2 = botData.skills) != null ? ref2 : ['*']);
              bot.enabled = (ref3 = botData.enabled) != null ? ref3 : true;
              bot.createdAt = botData.createdAt;
              bots.push(bot);
            } catch (error) {
              e = error;
              console.error('Error migrating bot:', e);
            }
          }
        }
        if (bots.length === 0) {
          defaultBot = Bot.createDefaultBot();
          bots.push(defaultBot);
          activeBotId = defaultBot.id;
        }
        return {bots, activeBotId};
      }

      saveBots(bots = null) {
        this._cache.bots = bots != null ? bots : this._cache.bots;
        this.storage.set('bots', this._cache.bots);
        this.storage.save('bots');
        return this;
      }

      getBot(botId) {
        var bots;
        bots = this.getBots();
        return bots.bots.find(function(b) {
          return b.id === botId;
        });
      }

      getActiveBot() {
        var active, bots;
        bots = this.getBots();
        active = bots.bots.find(function(b) {
          return b.id === bots.activeBotId;
        });
        return active != null ? active : bots.bots[0];
      }

      createBot(config) {
        var bot, bots, id, model, ref, ref1, ref2, ref3, ref4, ref5;
        if (!((ref = config.name) != null ? ref.trim() : void 0)) {
          return {
            error: 'Bot name is required'
          };
        }
        bots = this.getBots();
        id = Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
        model = (ref1 = config.model) != null ? ref1 : Model.create('glm-4-flash', 'zhipu');
        bot = new Bot(id, config.name.trim(), (ref2 = (ref3 = config.description) != null ? ref3.trim() : void 0) != null ? ref2 : '', model, (ref4 = config.systemPrompt) != null ? ref4 : 'You are a helpful assistant.', (ref5 = config.skills) != null ? ref5 : ['*']);
        bots.bots.push(bot);
        this.saveBots(bots);
        return bot;
      }

      updateBot(botId, updates) {
        var bot, bots;
        bots = this.getBots();
        bot = bots.bots.find(function(b) {
          return b.id === botId;
        });
        if (!bot) {
          return null;
        }
        bot.update(updates);
        this.saveBots(bots);
        return bot;
      }

      deleteBot(botId) {
        var bots, ref;
        bots = this.getBots();
        if (bots.bots.length <= 1) {
          return {
            error: 'Cannot delete the last bot'
          };
        }
        bots.bots = bots.bots.filter(function(b) {
          return b.id !== botId;
        });
        if (bots.activeBotId === botId) {
          bots.activeBotId = (ref = bots.bots[0]) != null ? ref.id : void 0;
        }
        this.saveBots(bots);
        return {
          success: true
        };
      }

      setActiveBot(botId) {
        var bot, bots;
        bots = this.getBots();
        bot = bots.bots.find(function(b) {
          return b.id === botId;
        });
        if (!bot) {
          return null;
        }
        bots.activeBotId = botId;
        this.saveBots(bots);
        return bot;
      }

      
        // Sessions
      getSessions() {
        var data;
        if (this._cache.sessions) {
          return this._cache.sessions;
        }
        data = this.storage.get('sessions');
        if ((data != null ? data.__class : void 0) === 'SessionManager') {
          this._cache.sessions = SessionManager.fromJSON(data);
        } else if (data) {
          this._cache.sessions = this._migrateSessions(data);
        } else {
          this._cache.sessions = new SessionManager();
        }
        return this._cache.sessions;
      }

      _migrateSessions(data) {
        var manager, ref, ref1, ref2, ref3, session, sessionData, sessionId;
        manager = new SessionManager();
        if (!data) {
          return manager;
        }
        for (sessionId in data) {
          sessionData = data[sessionId];
          if (!sessionData) {
            continue;
          }
          session = new Session(sessionId);
          session.title = (ref = sessionData.title) != null ? ref : '';
          session.messages = (ref1 = sessionData.messages) != null ? ref1 : [];
          session.createdAt = (ref2 = sessionData.createdAt) != null ? ref2 : Date.now();
          session.updatedAt = (ref3 = sessionData.updatedAt) != null ? ref3 : Date.now();
          if (sessionData.botId) {
            session.botId = sessionData.botId;
          }
          manager.addSession(session);
        }
        return manager;
      }

      saveSessions(sessions = null) {
        this._cache.sessions = sessions != null ? sessions : this._cache.sessions;
        this.storage.set('sessions', this._cache.sessions);
        this.storage.save('sessions');
        return this;
      }

      getSession(sessionId) {
        var manager, session;
        manager = this.getSessions();
        session = manager.getSession(sessionId);
        if (!session) {
          session = new Session(sessionId);
          manager.addSession(session);
          this.saveSessions(manager);
        }
        return session;
      }

      createSession() {
        var id, manager, session;
        id = Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
        session = new Session(id);
        manager = this.getSessions();
        manager.addSession(session);
        this.saveSessions(manager);
        return session;
      }

      addMessage(sessionId, role, content) {
        var manager, session;
        session = this.getSession(sessionId);
        session.addMessage(role, content);
        if (role === 'user' && !session.title) {
          session.title = content.substring(0, 50);
        }
        manager = this.getSessions();
        this.saveSessions(manager);
        return session;
      }

      deleteSession(sessionId) {
        var manager;
        manager = this.getSessions();
        manager.removeSession(sessionId);
        this.saveSessions(manager);
        return this;
      }

      listSessions() {
        var manager;
        manager = this.getSessions();
        return manager.getAllSessions();
      }

      
        // License
      getLicense() {
        var data;
        if (this._cache.license) {
          return this._cache.license;
        }
        data = this.storage.get('license');
        if ((data != null ? data.__class : void 0) === 'License') {
          this._cache.license = License.fromJSON(data);
        } else if (data) {
          this._cache.license = License.fromLegacy(data);
        } else {
          this._cache.license = new License();
        }
        return this._cache.license;
      }

      saveLicense(license = null) {
        this._cache.license = license != null ? license : this._cache.license;
        this.storage.set('license', this._cache.license);
        this.storage.save('license');
        return this;
      }

      getLicenseStatus() {
        var license;
        license = this.getLicense();
        return license.getStatus();
      }

      addPayment(paymentData) {
        var amount, currency, email, license, lifetimeThreshold, method, ref;
        license = this.getLicense();
        ({amount, method, email, currency} = paymentData);
        if (!(amount && amount > 0)) {
          return {
            error: 'Invalid amount'
          };
        }
        currency = currency != null ? currency : 'usd';
        if (license.currency && license.currency !== currency) {
          return {
            error: `Currency mismatch. Your account uses ${license.currency}`
          };
        }
        license.balance = ((ref = license.balance) != null ? ref : 0) + amount;
        license.paid = true;
        lifetimeThreshold = currency === 'cny' ? 216 : 36;
        if (amount >= lifetimeThreshold) {
          license.plan = 'lifetime';
        }
        if (license.paymentInfo == null) {
          license.paymentInfo = [];
        }
        license.paymentInfo.push({
          amount,
          method,
          email,
          currency,
          timestamp: new Date().toISOString()
        });
        this.saveLicense(license);
        return {
          success: true,
          balance: license.balance
        };
      }

      
        // Utility
      clear() {
        this._cache = {};
        this.storage.clear();
        return this;
      }

      getStoragePath() {
        return this.storage.getPath();
      }

    };

    TypedStorage.instance = null;

    return TypedStorage;

  }).call(this);

  module.exports = {TypedStorage};

}).call(this);
