// Generated by CoffeeScript 2.7.0
(function() {
  // CoffeeClaw - Main Process
  // Auto-configures OpenClaw on first run
  var BOT_TEMPLATES, BrowserWindow, INITIAL_BALANCE_CNY, INITIAL_BALANCE_USD, LICENSE_PRICES, MAX_HISTORY, MAX_SESSIONS, MODELS, PROVIDER_NAME_MAP, SKILLS, USD_TO_CNY, addToAgentSession, addToSession, agentDir, agentMdFile, agentModelsFile, agentSessionsFile, app, backupOpenClawConfig, backupSettings, botsFile, callAPI, callAPIWithMessages, callOpenClawAgent, checkNodeInstalled, checkNpmInstalled, checkOpenClaw, checkOpenClawInstalled, checkOpenClawPromise, checkWSLInstalled, configExists, configFile, configureFeishu, createAgentConfig, createBot, createDefaultConfig, createIdentity, createSession, createWindow, crypto, deleteBot, deleteSession, detectExistingFeishuConfig, ensureOpenClawConfig, exec, executeSkillFunction, exportAllSettings, fs, generateId, generateToken, getActiveBot, getAgentSession, getBackupData, getBot, getBotTemplates, getLicenseStatus, getOpenClawProviderConfig, getPlatform, getSession, getSkillFunctions, http, https, identityFile, importAllSettings, initLicense, installOpenClaw, ipcMain, isConfigured, isMac, isWindows, licenseFile, listSessions, listSettingsBackups, loadAgentSessions, loadBots, loadLicense, loadSessions, loadSettings, mainWindow, openclawDir, path, restoreSettings, saveAgentSessions, saveBots, saveLicense, saveSession, saveSessions, saveSettings, secreteDir, sendToOpenClaw, sessionsFile, setActiveBot, settingsFile, shell, spawn, startOpenClaw, syncFeishuConfigToOpenClaw, syncFeishuConfigToSettings, syncProvidersToOpenClaw, updateBot, workspaceDir;

  ({app, BrowserWindow, ipcMain, shell} = require('electron'));

  path = require('path');

  fs = require('fs');

  http = require('http');

  https = require('https');

  ({exec, spawn} = require('child_process'));

  crypto = require('crypto');

  openclawDir = path.join(process.env.HOME, '.openclaw');

  configFile = path.join(openclawDir, 'openclaw.json');

  workspaceDir = path.join(openclawDir, 'workspace');

  identityFile = path.join(workspaceDir, 'IDENTITY.md');

  agentDir = path.join(openclawDir, 'agents', 'main', 'agent');

  agentMdFile = path.join(agentDir, 'agent.md');

  agentModelsFile = path.join(agentDir, 'models.json');

  secreteDir = path.join(path.dirname(__dirname), '.secrete');

  settingsFile = path.join(secreteDir, 'settings.json');

  sessionsFile = path.join(secreteDir, 'sessions.json');

  botsFile = path.join(secreteDir, 'bots.json');

  licenseFile = path.join(secreteDir, 'license.json');

  agentSessionsFile = path.join(secreteDir, 'agent-sessions.json');

  USD_TO_CNY = 6;

  LICENSE_PRICES = {
    yearly_usd: 12,
    yearly_cny: 12 * USD_TO_CNY,
    lifetime_usd: 36,
    lifetime_cny: 36 * USD_TO_CNY,
    btc_address: null,
    monthly_usd: 1,
    monthly_cny: 1 * USD_TO_CNY
  };

  INITIAL_BALANCE_USD = 1;

  INITIAL_BALANCE_CNY = 1 * USD_TO_CNY;

  MAX_HISTORY = 100;

  MAX_SESSIONS = 50;

  isWindows = process.platform === 'win32';

  isMac = process.platform === 'darwin';

  generateToken = function() {
    return crypto.randomBytes(24).toString('hex');
  };

  generateId = function() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
  };

  loadSettings = function() {
    var data, e, settings;
    try {
      if (fs.existsSync(settingsFile)) {
        data = fs.readFileSync(settingsFile, 'utf8');
        settings = JSON.parse(data);
        if (settings.token && settings.apiKey) {
          return settings;
        }
      }
    } catch (error) {
      e = error;
      console.error('Error loading settings:', e);
    }
    return {};
  };

  saveSettings = function(settings) {
    var e;
    try {
      fs.mkdirSync(secreteDir, {
        recursive: true
      });
      return fs.writeFileSync(settingsFile, JSON.stringify(settings, null, 2));
    } catch (error) {
      e = error;
      return console.error('Error saving settings:', e);
    }
  };

  backupSettings = function() {
    var backup, backupData, backupFile, backups, e, i, j, len, timestamp;
    try {
      timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      backupFile = path.join(secreteDir, `backup.${timestamp}.json`);
      backupData = {
        version: '1.0',
        backedUpAt: new Date().toISOString(),
        settings: fs.existsSync(settingsFile) ? JSON.parse(fs.readFileSync(settingsFile, 'utf8')) : {},
        sessions: fs.existsSync(sessionsFile) ? JSON.parse(fs.readFileSync(sessionsFile, 'utf8')) : {
          sessions: []
        },
        bots: loadBots(),
        license: loadLicense()
      };
      fs.writeFileSync(backupFile, JSON.stringify(backupData, null, 2));
      backups = fs.readdirSync(secreteDir).filter(function(f) {
        return f.startsWith('backup.') && f.endsWith('.json') && f !== 'bots.json';
      }).sort().reverse();
      for (i = j = 0, len = backups.length; j < len; i = ++j) {
        backup = backups[i];
        if (i >= 5) {
          fs.unlinkSync(path.join(secreteDir, backup));
        }
      }
      console.log(`Full backup created: ${backupFile}`);
      return true;
    } catch (error) {
      e = error;
      console.error('Error backing up:', e);
      return false;
    }
  };

  restoreSettings = function(backupName, options = {}) {
    var backupPath, data, e, restoreBots, restoreLicense, restoreSessions;
    try {
      backupPath = path.join(secreteDir, backupName);
      if (fs.existsSync(backupPath)) {
        data = JSON.parse(fs.readFileSync(backupPath, 'utf8'));
        restoreSettings = options.settings != null ? options.settings : true;
        restoreSessions = options.sessions != null ? options.sessions : true;
        restoreBots = options.bots != null ? options.bots : true;
        restoreLicense = options.license != null ? options.license : true;
        if (data.settings && restoreSettings) {
          fs.writeFileSync(settingsFile, JSON.stringify(data.settings, null, 2));
        }
        if (data.sessions && restoreSessions) {
          fs.writeFileSync(sessionsFile, JSON.stringify(data.sessions, null, 2));
        }
        if (data.bots && restoreBots) {
          fs.writeFileSync(botsFile, JSON.stringify(data.bots, null, 2));
        }
        if (data.license && restoreLicense) {
          fs.writeFileSync(licenseFile, JSON.stringify(data.license, null, 2));
        }
        console.log(`Backup restored from: ${backupName}`);
        return true;
      }
      return false;
    } catch (error) {
      e = error;
      console.error('Error restoring backup:', e);
      return false;
    }
  };

  getBackupData = function(backupName) {
    var backupPath, e;
    try {
      backupPath = path.join(secreteDir, backupName);
      if (fs.existsSync(backupPath)) {
        return JSON.parse(fs.readFileSync(backupPath, 'utf8'));
      } else {
        return null;
      }
    } catch (error) {
      e = error;
      console.error('Error reading backup:', e);
      return null;
    }
  };

  listSettingsBackups = function() {
    try {
      return fs.readdirSync(secreteDir).filter(function(f) {
        return f.startsWith('backup.') && f.endsWith('.json') && f !== 'bots.json';
      }).sort().reverse();
    } catch (error) {
      return [];
    }
  };

  exportAllSettings = function() {
    var bots, e, exportData, license, sessions, settings;
    try {
      settings = loadSettings();
      sessions = fs.existsSync(sessionsFile) ? JSON.parse(fs.readFileSync(sessionsFile, 'utf8')) : {
        sessions: []
      };
      bots = loadBots();
      license = loadLicense();
      exportData = {
        version: '1.0',
        exportedAt: new Date().toISOString(),
        settings: settings,
        sessions: sessions,
        bots: bots,
        license: license
      };
      return exportData;
    } catch (error) {
      e = error;
      console.error('Error exporting settings:', e);
      return null;
    }
  };

  importAllSettings = function(data, options = {}) {
    var e, importBots, importLicense, importSessions, importSettings;
    try {
      importSettings = options.settings != null ? options.settings : true;
      importSessions = options.sessions != null ? options.sessions : true;
      importBots = options.bots != null ? options.bots : true;
      importLicense = options.license != null ? options.license : true;
      if (data.settings && importSettings) {
        saveSettings(data.settings);
      }
      if (data.sessions && importSessions) {
        fs.writeFileSync(sessionsFile, JSON.stringify(data.sessions, null, 2));
      }
      if (data.bots && importBots) {
        fs.writeFileSync(botsFile, JSON.stringify(data.bots, null, 2));
      }
      if (data.license && importLicense) {
        saveLicense(data.license);
      }
      return true;
    } catch (error) {
      e = error;
      console.error('Error importing settings:', e);
      return false;
    }
  };

  loadLicense = function() {
    var data, e;
    try {
      if (fs.existsSync(licenseFile)) {
        data = fs.readFileSync(licenseFile, 'utf8');
        return JSON.parse(data);
      }
    } catch (error) {
      e = error;
      console.error('Error loading license:', e);
    }
    return null;
  };

  saveLicense = function(license) {
    var e;
    try {
      fs.mkdirSync(secreteDir, {
        recursive: true
      });
      return fs.writeFileSync(licenseFile, JSON.stringify(license, null, 2));
    } catch (error) {
      e = error;
      return console.error('Error saving license:', e);
    }
  };

  initLicense = function() {
    var license, newLicense;
    license = loadLicense();
    if (license) {
      return license;
    }
    newLicense = {
      deviceId: generateId(),
      createdAt: new Date().toISOString(),
      balance: INITIAL_BALANCE_USD,
      currency: 'usd',
      paid: false,
      plan: null,
      lastDeduction: null
    };
    saveLicense(newLicense);
    return newLicense;
  };

  getLicenseStatus = function() {
    var createdAt, currentBalance, deduction, lastDeduction, license, monthsSinceCreation, monthsSinceLastDeduction, now;
    license = loadLicense();
    if (!license) {
      license = initLicense();
    }
    if (license.paid && license.plan === 'lifetime') {
      return {
        status: 'lifetime',
        balance: 0,
        paid: true,
        plan: 'lifetime',
        showIndicator: false
      };
    }
    if (license.balance == null) {
      license.balance = INITIAL_BALANCE_USD;
      saveLicense(license);
    }
    currentBalance = license.balance;
    now = new Date();
    createdAt = new Date(license.createdAt);
    monthsSinceCreation = (now.getFullYear() - createdAt.getFullYear()) * 12 + (now.getMonth() - createdAt.getMonth());
    if (license.lastDeduction) {
      lastDeduction = new Date(license.lastDeduction);
      monthsSinceLastDeduction = (now.getFullYear() - lastDeduction.getFullYear()) * 12 + (now.getMonth() - lastDeduction.getMonth());
    } else {
      monthsSinceLastDeduction = monthsSinceCreation;
    }
    if (monthsSinceLastDeduction >= 1) {
      deduction = Math.floor(monthsSinceLastDeduction);
      currentBalance = license.balance - deduction;
      if (currentBalance !== license.balance) {
        license.balance = currentBalance;
        license.lastDeduction = now.toISOString();
        saveLicense(license);
      }
    }
    return {
      status: currentBalance > 0 ? 'active' : 'overdue',
      balance: currentBalance,
      paid: license.paid,
      plan: license.plan,
      showIndicator: true,
      currency: license.currency || 'usd'
    };
  };

  loadSessions = function() {
    var data, e;
    try {
      if (fs.existsSync(sessionsFile)) {
        data = fs.readFileSync(sessionsFile, 'utf8');
        return JSON.parse(data);
      }
    } catch (error) {
      e = error;
      console.error('Error loading sessions:', e);
    }
    return {};
  };

  saveSessions = function(sessions) {
    var e;
    try {
      fs.mkdirSync(secreteDir, {
        recursive: true
      });
      return fs.writeFileSync(sessionsFile, JSON.stringify(sessions, null, 2));
    } catch (error) {
      e = error;
      return console.error('Error saving sessions:', e);
    }
  };

  getSession = function(sessionId) {
    var sessions;
    sessions = loadSessions();
    return sessions[sessionId] || {
      id: sessionId,
      messages: [],
      createdAt: Date.now()
    };
  };

  saveSession = function(sessionId, session) {
    var oldest, sessionIds, sessions;
    sessions = loadSessions();
    session.messages = session.messages.slice(-MAX_HISTORY);
    sessions[sessionId] = session;
    sessionIds = Object.keys(sessions);
    if (sessionIds.length > MAX_SESSIONS) {
      oldest = sessionIds.sort(function(a, b) {
        return sessions[a].createdAt - sessions[b].createdAt;
      })[0];
      delete sessions[oldest];
    }
    return saveSessions(sessions);
  };

  addToSession = function(sessionId, role, content) {
    var session;
    session = getSession(sessionId);
    if (!session.messages) {
      session.messages = [];
    }
    session.messages.push({
      role: role,
      content: content,
      timestamp: Date.now()
    });
    if (!session.title && role === 'user') {
      session.title = content.substring(0, 50);
    }
    if (!session.createdAt) {
      session.createdAt = Date.now();
    }
    session.updatedAt = Date.now();
    saveSession(sessionId, session);
    return session;
  };

  createSession = function() {
    var session, sessionId;
    sessionId = generateId();
    session = {
      id: sessionId,
      title: '',
      messages: [],
      createdAt: Date.now(),
      updatedAt: Date.now()
    };
    saveSession(sessionId, session);
    return session;
  };

  loadAgentSessions = function() {
    var data, e;
    try {
      if (fs.existsSync(agentSessionsFile)) {
        data = fs.readFileSync(agentSessionsFile, 'utf8');
        return JSON.parse(data);
      }
    } catch (error) {
      e = error;
      console.error('Error loading agent sessions:', e);
    }
    return {};
  };

  saveAgentSessions = function(sessions) {
    var e;
    try {
      fs.mkdirSync(secreteDir, {
        recursive: true
      });
      return fs.writeFileSync(agentSessionsFile, JSON.stringify(sessions, null, 2));
    } catch (error) {
      e = error;
      return console.error('Error saving agent sessions:', e);
    }
  };

  getAgentSession = function(sessionId) {
    var sessions;
    sessions = loadAgentSessions();
    return sessions[sessionId] || {
      id: sessionId,
      messages: [],
      openclawSessionId: sessionId,
      createdAt: Date.now()
    };
  };

  addToAgentSession = function(sessionId, role, content) {
    var session, sessions;
    sessions = loadAgentSessions();
    session = sessions[sessionId] || {
      id: sessionId,
      messages: [],
      openclawSessionId: sessionId
    };
    session.messages.push({
      role: role,
      content: content,
      timestamp: Date.now(),
      source: 'openclaw-agent'
    });
    if (!session.title && role === 'user') {
      session.title = content.substring(0, 50);
    }
    if (!session.createdAt) {
      session.createdAt = Date.now();
    }
    session.updatedAt = Date.now();
    sessions[sessionId] = session;
    saveAgentSessions(sessions);
    return session;
  };

  BOT_TEMPLATES = [
    {
      id: 'openclaw-agent',
      name: 'OpenClaw Agent',
      description: 'Direct channel to OpenClaw Agent with full development tools',
      model: 'openclaw-agent',
      systemPrompt: 'You are the OpenClaw Agent, a powerful AI assistant with access to development tools, file system, and code analysis capabilities.',
      skills: ['*'],
      isAgent: true
    },
    {
      id: 'code-helper',
      name: 'Code Helper',
      description: 'Expert assistant for Swift, CoffeeScript, and Python development',
      model: 'glm-4-flash',
      systemPrompt: 'You are an expert software developer specializing in Swift, CoffeeScript, and Python. When asked about files or code, ALWAYS use your available tools FIRST: use list_files to explore directories, read_file to read source code, and execute for shell commands. Do not give generic answers - read the actual files and provide specific insights. Help with coding tasks, debugging, code review, and best practices. Always provide clean, well-commented code examples.',
      skills: ['fs',
    'code',
    'git']
    },
    {
      id: 'writer',
      name: 'Creative Writer',
      description: 'Creative writing assistant for content creation',
      model: 'glm-4-flash',
      systemPrompt: 'You are a creative writing assistant. You help with blog posts, articles, stories, and other content. You have excellent grammar and style. You can adapt to different tones and audiences. Always be creative and engaging.',
      skills: ['*']
    },
    {
      id: 'translator',
      name: 'Translator',
      description: 'Multilingual translation assistant',
      model: 'glm-4-flash',
      systemPrompt: 'You are a professional translator. You translate text accurately while preserving meaning, tone, and cultural context. You support English, Chinese, and Esperanto. Always ask for clarification if the source text is ambiguous.',
      skills: ['*']
    }
  ];

  getBotTemplates = function() {
    return BOT_TEMPLATES;
  };

  loadBots = function() {
    var data, e;
    try {
      if (fs.existsSync(botsFile)) {
        data = fs.readFileSync(botsFile, 'utf8');
        return JSON.parse(data);
      }
    } catch (error) {
      e = error;
      console.error('Error loading bots:', e);
    }
    return {
      bots: [
        {
          id: 'default',
          name: 'General Assistant',
          description: 'A helpful general-purpose assistant',
          model: 'glm-4-flash',
          systemPrompt: 'You are a helpful assistant. Be concise and helpful.',
          skills: ['*'],
          enabled: true,
          createdAt: new Date().toISOString()
        }
      ],
      activeBotId: 'default'
    };
  };

  saveBots = function(botsData) {
    var e;
    try {
      fs.mkdirSync(secreteDir, {
        recursive: true
      });
      return fs.writeFileSync(botsFile, JSON.stringify(botsData, null, 2));
    } catch (error) {
      e = error;
      return console.error('Error saving bots:', e);
    }
  };

  getBot = function(botId) {
    var botsData;
    botsData = loadBots();
    return botsData.bots.find(function(b) {
      return b.id === botId;
    });
  };

  getActiveBot = function() {
    var activeBot, botsData;
    botsData = loadBots();
    activeBot = botsData.bots.find(function(b) {
      return b.id === botsData.activeBotId;
    });
    return activeBot || botsData.bots[0];
  };

  createBot = function(botConfig) {
    var botsData, newBot, ref, ref1;
    if (!((ref = botConfig.name) != null ? ref.trim() : void 0)) {
      return {
        error: 'Bot name is required'
      };
    }
    botsData = loadBots();
    newBot = {
      id: generateId(),
      name: botConfig.name.trim(),
      description: ((ref1 = botConfig.description) != null ? ref1.trim() : void 0) || '',
      model: botConfig.model || 'glm-4-flash',
      systemPrompt: botConfig.systemPrompt || 'You are a helpful assistant.',
      skills: botConfig.skills || ['*'],
      enabled: true,
      createdAt: new Date().toISOString()
    };
    if (botConfig.isAgent) {
      newBot.isAgent = true;
    }
    botsData.bots.push(newBot);
    saveBots(botsData);
    return newBot;
  };

  updateBot = function(botId, updates) {
    var botIndex, botsData;
    botsData = loadBots();
    botIndex = botsData.bots.findIndex(function(b) {
      return b.id === botId;
    });
    if (botIndex >= 0) {
      botsData.bots[botIndex] = {
        ...botsData.bots[botIndex],
        ...updates,
        updatedAt: new Date().toISOString()
      };
      saveBots(botsData);
      return botsData.bots[botIndex];
    }
    return null;
  };

  deleteBot = function(botId) {
    var botsData, ref;
    botsData = loadBots();
    if (botsData.bots.length <= 1) {
      return {
        success: false,
        error: 'Cannot delete the last bot'
      };
    }
    botsData.bots = botsData.bots.filter(function(b) {
      return b.id !== botId;
    });
    if (botsData.activeBotId === botId) {
      botsData.activeBotId = (ref = botsData.bots[0]) != null ? ref.id : void 0;
    }
    saveBots(botsData);
    return {
      success: true
    };
  };

  setActiveBot = function(botId) {
    var bot, botsData;
    botsData = loadBots();
    bot = botsData.bots.find(function(b) {
      return b.id === botId;
    });
    if (bot) {
      botsData.activeBotId = botId;
      saveBots(botsData);
      return bot;
    }
    return null;
  };

  SKILLS = {
    fs: {
      list_files: {
        description: 'List all files and directories in a given path. Use this to explore the file system.',
        parameters: {
          type: 'object',
          properties: {
            path: {
              type: 'string',
              description: 'Directory path to list (default: current directory)'
            }
          },
          required: []
        },
        handler: function(args) {
          var e, files, results, targetPath;
          try {
            targetPath = args.path || process.cwd();
            files = fs.readdirSync(targetPath, {
              withFileTypes: true
            });
            results = files.map(function(f) {
              return {
                type: f.isDirectory() ? 'directory' : 'file',
                name: f.name
              };
            });
            return {
              success: true,
              files: results,
              path: targetPath
            };
          } catch (error) {
            e = error;
            return {
              success: false,
              error: e.message
            };
          }
        }
      },
      read_file: {
        description: 'Read and return the contents of a file. Use this to read source code, config files, etc.',
        parameters: {
          type: 'object',
          properties: {
            path: {
              type: 'string',
              description: 'File path to read (required)'
            }
          },
          required: ['path']
        },
        handler: function(args) {
          var content, e;
          try {
            content = fs.readFileSync(args.path, 'utf8');
            return {
              success: true,
              content: content.substring(0, 10000)
            };
          } catch (error) {
            e = error;
            return {
              success: false,
              error: e.message
            };
          }
        }
      }
    },
    code: {
      execute: {
        description: 'Execute a shell command and return the output. Use for commands like ls, git, npm, etc.',
        parameters: {
          type: 'object',
          properties: {
            command: {
              type: 'string',
              description: 'Shell command to execute (required)'
            },
            cwd: {
              type: 'string',
              description: 'Working directory (default: current directory)'
            }
          },
          required: ['command']
        },
        handler: function(args) {
          var e, result;
          try {
            result = require('child_process').execSync(args.command, {
              cwd: args.cwd || process.cwd(),
              encoding: 'utf8',
              timeout: 30000
            });
            return {
              success: true,
              output: result.substring(0, 5000)
            };
          } catch (error) {
            e = error;
            return {
              success: false,
              error: e.message,
              output: e.stdout || ''
            };
          }
        }
      }
    },
    git: {
      status: {
        description: 'Get git status showing modified, added, and untracked files.',
        parameters: {
          type: 'object',
          properties: {
            cwd: {
              type: 'string',
              description: 'Working directory (default: current directory)'
            }
          }
        },
        handler: function(args) {
          var e, result;
          try {
            result = require('child_process').execSync('git status --short', {
              cwd: args.cwd || process.cwd(),
              encoding: 'utf8'
            });
            return {
              success: true,
              status: result
            };
          } catch (error) {
            e = error;
            return {
              success: false,
              error: e.message
            };
          }
        }
      },
      log: {
        description: 'Get recent git commit history.',
        parameters: {
          type: 'object',
          properties: {
            count: {
              type: 'integer',
              description: 'Number of commits to show (default: 10)'
            },
            cwd: {
              type: 'string',
              description: 'Working directory'
            }
          }
        },
        handler: function(args) {
          var count, e, result;
          try {
            count = args.count || 10;
            result = require('child_process').execSync(`git log --oneline -${count}`, {
              cwd: args.cwd || process.cwd(),
              encoding: 'utf8'
            });
            return {
              success: true,
              log: result
            };
          } catch (error) {
            e = error;
            return {
              success: false,
              error: e.message
            };
          }
        }
      }
    }
  };

  getSkillFunctions = function(botSkills) {
    var funcDef, funcName, functions, j, len, skill, skillName;
    if (!(botSkills && botSkills[0] !== '*')) {
      return [];
    }
    functions = [];
    for (j = 0, len = botSkills.length; j < len; j++) {
      skillName = botSkills[j];
      skill = SKILLS[skillName];
      if (!skill) {
        continue;
      }
      for (funcName in skill) {
        funcDef = skill[funcName];
        functions.push({
          name: funcName,
          description: funcDef.description,
          parameters: funcDef.parameters
        });
      }
    }
    return functions;
  };

  executeSkillFunction = function(name, args, botSkills) {
    var j, len, ref, skill, skillName, skillName2;
    ref = botSkills || ['*'];
    for (j = 0, len = ref.length; j < len; j++) {
      skillName = ref[j];
      if (skillName === '*') {
        for (skillName2 in SKILLS) {
          skill = SKILLS[skillName2];
          if (skill[name]) {
            return skill[name].handler(args);
          }
        }
      } else {
        skill = SKILLS[skillName];
        if (skill != null ? skill[name] : void 0) {
          return skill[name].handler(args);
        }
      }
    }
    return {
      success: false,
      error: `Unknown function: ${name}`
    };
  };

  deleteSession = function(sessionId) {
    var sessions;
    sessions = loadSessions();
    delete sessions[sessionId];
    return saveSessions(sessions);
  };

  listSessions = function() {
    var key, result, session, sessions;
    sessions = loadSessions();
    result = [];
    for (key in sessions) {
      session = sessions[key];
      result.push(session);
    }
    result.sort(function(a, b) {
      return (b.updatedAt || 0) - (a.updatedAt || 0);
    });
    return result;
  };

  checkOpenClaw = function(callback) {
    var req;
    req = http.get('http://127.0.0.1:18789/health', function(res) {
      return callback(true);
    });
    req.on('error', function() {
      return callback(false);
    });
    return req.setTimeout(2000, function() {
      req.destroy();
      return callback(false);
    });
  };

  checkOpenClawPromise = function() {
    return new Promise(function(resolve) {
      return checkOpenClaw(resolve);
    });
  };

  startOpenClaw = function() {
    return new Promise(function(resolve) {
      var attempts, check, child, maxAttempts;
      console.log('Starting OpenClaw gateway...');
      child = spawn('openclaw', ['gateway', '--dev'], {
        detached: true,
        stdio: 'ignore'
      });
      child.unref();
      attempts = 0;
      maxAttempts = 30;
      check = function() {
        attempts++;
        return checkOpenClaw(function(running) {
          if (running) {
            return resolve(true);
          } else if (attempts < maxAttempts) {
            return setTimeout(check, 1000);
          } else {
            return resolve(false);
          }
        });
      };
      return setTimeout(check, 2000);
    });
  };

  configExists = function() {
    try {
      return fs.existsSync(configFile);
    } catch (error) {
      return false;
    }
  };

  isConfigured = function() {
    var settings;
    settings = loadSettings();
    return settings.token && settings.apiKey;
  };

  createDefaultConfig = function(apiKey) {
    var defaultConfig, key, settings, token;
    console.log('Creating OpenClaw config...');
    settings = loadSettings();
    token = settings.token || generateToken();
    key = apiKey || settings.apiKey || '';
    if (!fs.existsSync(openclawDir)) {
      fs.mkdirSync(openclawDir, {
        recursive: true
      });
    }
    if (!fs.existsSync(workspaceDir)) {
      fs.mkdirSync(workspaceDir, {
        recursive: true
      });
    }
    if (!fs.existsSync(agentDir)) {
      fs.mkdirSync(agentDir, {
        recursive: true
      });
    }
    defaultConfig = {
      meta: {
        lastTouchedVersion: '2026.3.2',
        lastTouchedAt: new Date().toISOString()
      },
      env: {},
      models: {
        providers: {}
      },
      agents: {
        defaults: {
          model: {
            primary: 'glm/GLM-4-Flash'
          },
          models: {
            'glm/GLM-4-Flash': {}
          },
          compaction: {
            mode: 'safeguard'
          }
        }
      },
      commands: {
        native: 'auto',
        nativeSkills: 'auto',
        restart: true,
        ownerDisplay: 'raw'
      },
      channels: {
        feishu: {
          enabled: false
        }
      },
      gateway: {
        mode: 'local',
        http: {
          endpoints: {
            chatCompletions: {
              enabled: true
            }
          }
        },
        auth: {
          mode: 'token',
          token: token
        }
      }
    };
    if (key) {
      defaultConfig.env.ZHIPU_API_KEY = key;
      defaultConfig.models.providers.glm = {
        baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
        apiKey: key,
        api: 'openai-completions',
        models: [
          {
            id: 'GLM-4-Flash',
            name: 'GLM 4 Flash'
          },
          {
            id: 'GLM-4.5-air',
            name: 'GLM 4.5 air'
          },
          {
            id: 'GLM-4.7',
            name: 'GLM 4.7'
          }
        ]
      };
    }
    fs.writeFileSync(configFile, JSON.stringify(defaultConfig, null, 2));
    console.log('Config created at:', configFile);
    settings.token = token;
    if (key) {
      settings.apiKey = key;
    }
    saveSettings(settings);
    createIdentity();
    createAgentConfig(key);
    return token;
  };

  createIdentity = function() {
    var identity;
    if (fs.existsSync(identityFile)) {
      return;
    }
    console.log('Creating identity...');
    identity = `# IDENTITY.md - Who Am I?

- **Name:** CoffeeClaw
- **Creature:** AI Assistant
- **Vibe:** helpful and friendly
- **Emoji:** ☕

I am a desktop AI assistant powered by OpenClaw and Zhipu GLM models.
I can help you with various tasks and answer your questions.`;
    fs.writeFileSync(identityFile, identity);
    return console.log('Identity created at:', identityFile);
  };

  createAgentConfig = function(apiKey) {
    var agentMd, agentModels, key;
    key = apiKey || '';
    agentModels = {
      providers: {}
    };
    if (key) {
      agentModels.providers.glm = {
        baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
        apiKey: key,
        api: 'openai-completions',
        models: [
          {
            id: 'GLM-4-Flash',
            name: 'GLM 4 Flash',
            reasoning: false,
            input: ['text'],
            cost: {
              input: 0,
              output: 0,
              cacheRead: 0,
              cacheWrite: 0
            },
            contextWindow: 200000,
            maxTokens: 8192,
            api: 'openai-completions'
          }
        ]
      };
    }
    fs.writeFileSync(agentModelsFile, JSON.stringify(agentModels, null, 2));
    agentMd = `# Agent Configuration

## Identity
You are a helpful AI assistant running on the user's local machine. You are powered by GLM-4-Flash model from Zhipu AI.

## Capabilities
- File system access (sandboxed)
- System command execution (limited)
- Answer questions and provide assistance

## Safety Rules
- Confirm destructive actions
- Respect user privacy
- Be helpful and concise

## Communication
- Respond in the same language the user uses
- Be friendly and professional
- Provide clear and accurate information`;
    fs.writeFileSync(agentMdFile, agentMd);
    return console.log('Agent config created');
  };

  checkOpenClawInstalled = function() {
    return new Promise(function(resolve) {
      var cmd;
      cmd = isWindows ? 'where openclaw' : 'which openclaw';
      return exec(cmd, function(err) {
        return resolve(!err);
      });
    });
  };

  checkNodeInstalled = function() {
    return new Promise(function(resolve) {
      return exec('node --version', function(err, stdout) {
        return resolve(!err);
      });
    });
  };

  checkNpmInstalled = function() {
    return new Promise(function(resolve) {
      return exec('npm --version', function(err, stdout) {
        return resolve(!err);
      });
    });
  };

  checkWSLInstalled = function() {
    return new Promise(function(resolve) {
      return exec('wsl --list', function(err, stdout) {
        return resolve(!err);
      });
    });
  };

  getPlatform = function() {
    return process.platform;
  };

  installOpenClaw = function() {
    return new Promise(function(resolve, reject) {
      console.log('Installing OpenClaw...');
      return exec('npm install -g openclaw', function(err, stdout, stderr) {
        if (err) {
          console.error('Install error:', stderr);
          return reject(err);
        } else {
          console.log('OpenClaw installed successfully');
          return resolve(true);
        }
      });
    });
  };

  MODELS = {
    zhipu: {
      name: 'Zhipu GLM',
      models: [
        {
          id: 'glm-4-flash',
          name: 'GLM-4-Flash (Free)',
          free: true
        },
        {
          id: 'glm-4-plus',
          name: 'GLM-4-Plus'
        },
        {
          id: 'glm-4-air',
          name: 'GLM-4-Air'
        }
      ],
      baseUrl: 'open.bigmodel.cn',
      apiPath: '/api/paas/v4/chat/completions'
    },
    openrouter: {
      name: 'OpenRouter',
      models: [
        {
          id: 'openrouter/auto',
          name: 'Auto (Best Free)',
          free: true
        },
        {
          id: 'google/gemini-2.0-flash-001',
          name: 'Gemini 2.0 Flash',
          free: true
        },
        {
          id: 'meta-llama/llama-3.3-70b-instruct',
          name: 'Llama 3.3 70B',
          free: true
        },
        {
          id: 'deepseek/deepseek-chat',
          name: 'DeepSeek Chat',
          free: true
        }
      ],
      baseUrl: 'openrouter.ai',
      apiPath: '/api/v1/chat/completions'
    },
    openai: {
      name: 'OpenAI',
      models: [
        {
          id: 'gpt-4o-mini',
          name: 'GPT-4o Mini'
        },
        {
          id: 'gpt-4o',
          name: 'GPT-4o'
        },
        {
          id: 'gpt-4-turbo',
          name: 'GPT-4 Turbo'
        }
      ],
      baseUrl: 'api.openai.com',
      apiPath: '/v1/chat/completions'
    },
    deepseek: {
      name: 'DeepSeek',
      models: [
        {
          id: 'deepseek-chat',
          name: 'DeepSeek Chat'
        },
        {
          id: 'deepseek-coder',
          name: 'DeepSeek Coder'
        }
      ],
      baseUrl: 'api.deepseek.com',
      apiPath: '/v1/chat/completions'
    }
  };

  callOpenClawAgent = function(sessionId, message) {
    return new Promise(function(resolve, reject) {
      var cmd;
      cmd = `openclaw agent --local --session-id \"${sessionId}\" --message ${JSON.stringify(message)} --json 2>/dev/null`;
      return exec(cmd, {
        maxBuffer: 1024 * 1024 * 10
      }, function(err, stdout, stderr) {
        var e, j, len, p, payloads, ref, ref1, ref2, result, text;
        if (err) {
          console.error('OpenClaw Agent error:', err);
          reject(new Error(err.message));
          return;
        }
        try {
          result = JSON.parse(stdout);
          payloads = (result != null ? (ref = result.result) != null ? ref.payloads : void 0 : void 0) || [];
          text = '';
          for (j = 0, len = payloads.length; j < len; j++) {
            p = payloads[j];
            if (p.type === 'text' || p.text) {
              text += p.text || p.content || '';
            }
          }
          if (!text && (result != null ? (ref1 = result.result) != null ? (ref2 = ref1.meta) != null ? ref2.agentMeta : void 0 : void 0 : void 0)) {
            text = 'Response received (check session for details)';
          }
          return resolve(text || 'No response');
        } catch (error) {
          e = error;
          return resolve(stdout.trim() || 'Response received');
        }
      });
    });
  };

  callAPI = async function(sessionId, message, settings, bot = null) {
    var model;
    model = (bot != null ? bot.model : void 0) || settings.model || 'glm-4-flash';
    if (model === 'openclaw-agent' || (bot != null ? bot.isAgent : void 0)) {
      return (await callOpenClawAgent(sessionId, message));
    }
    return new Promise(function(resolve, reject) {
      var apiKey, config, functions, j, len, messages, msg, options, postData, provider, providerConfig, ref, req, session, systemPrompt;
      provider = settings.activeProvider || settings.provider || 'zhipu';
      if (settings.providers && settings.providers[provider]) {
        providerConfig = settings.providers[provider];
        apiKey = providerConfig.apiKey;
        model = (bot != null ? bot.model : void 0) || providerConfig.model || 'glm-4-flash';
      } else {
        apiKey = settings.apiKey;
        model = (bot != null ? bot.model : void 0) || settings.model || 'glm-4-flash';
      }
      config = MODELS[provider];
      if (!config) {
        return reject(new Error(`Unknown provider: ${provider}`));
      }
      session = getSession(sessionId);
      systemPrompt = (bot != null ? bot.systemPrompt : void 0) || 'You are CoffeeClaw, a helpful AI assistant. Respond in the same language the user uses. Be friendly and helpful.';
      messages = [
        {
          role: 'system',
          content: systemPrompt
        }
      ];
      if (session.messages) {
        ref = session.messages;
        for (j = 0, len = ref.length; j < len; j++) {
          msg = ref[j];
          messages.push({
            role: msg.role,
            content: msg.content
          });
        }
      }
      messages.push({
        role: 'user',
        content: message
      });
      functions = getSkillFunctions(bot != null ? bot.skills : void 0);
      postData = {
        model: model,
        messages: messages,
        stream: false
      };
      if (functions.length > 0) {
        postData.tools = functions.map(function(f) {
          return {
            type: 'function',
            function: f
          };
        });
        postData.tool_choice = 'auto';
        postData.do_sample = false;
      }
      postData = JSON.stringify(postData);
      options = {
        hostname: config.baseUrl,
        port: 443,
        path: config.apiPath,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
          'Content-Length': Buffer.byteLength(postData)
        }
      };
      if (provider === 'openrouter') {
        options.headers['HTTP-Referer'] = 'https://coffeeclaw.app';
        options.headers['X-Title'] = 'CoffeeClaw';
      }
      req = https.request(options, function(res) {
        var data;
        data = '';
        res.on('data', function(chunk) {
          return data += chunk;
        });
        return res.on('end', function() {
          var choice, e, funcArgs, funcName, funcResult, ref1, result, toolCall;
          try {
            result = JSON.parse(data);
            if (result.error) {
              return reject(new Error(result.error.message || 'API error'));
            } else if (result.choices && result.choices[0]) {
              choice = result.choices[0];
              if ((ref1 = choice.message) != null ? ref1.tool_calls : void 0) {
                toolCall = choice.message.tool_calls[0];
                if ((toolCall != null ? toolCall.type : void 0) === 'function') {
                  funcName = toolCall.function.name;
                  funcArgs = JSON.parse(toolCall.function.arguments);
                  funcResult = executeSkillFunction(funcName, funcArgs, bot != null ? bot.skills : void 0);
                  messages.push(choice.message);
                  messages.push({
                    role: 'tool',
                    content: JSON.stringify(funcResult),
                    tool_call_id: toolCall.id
                  });
                  callAPIWithMessages(sessionId, messages, settings, bot, apiKey).then(resolve).catch(reject);
                  return;
                }
              }
              return resolve(choice.message.content);
            } else {
              return reject(new Error('Unknown response format'));
            }
          } catch (error) {
            e = error;
            return reject(e);
          }
        });
      });
      req.on('error', reject);
      req.setTimeout(60000, function() {
        req.destroy();
        return reject(new Error('Request timeout'));
      });
      req.write(postData);
      return req.end();
    });
  };

  callAPIWithMessages = function(sessionId, messages, settings, bot, apiKey) {
    return new Promise(function(resolve, reject) {
      var config, model, options, postData, provider, providerConfig, req;
      provider = settings.activeProvider || settings.provider || 'zhipu';
      if (settings.providers && settings.providers[provider]) {
        providerConfig = settings.providers[provider];
        model = (bot != null ? bot.model : void 0) || providerConfig.model || 'glm-4-flash';
      } else {
        model = (bot != null ? bot.model : void 0) || settings.model || 'glm-4-flash';
      }
      config = MODELS[provider];
      postData = {
        model: model,
        messages: messages,
        stream: false,
        do_sample: false
      };
      postData = JSON.stringify(postData);
      options = {
        hostname: config.baseUrl,
        port: 443,
        path: config.apiPath,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
          'Content-Length': Buffer.byteLength(postData)
        }
      };
      if (provider === 'openrouter') {
        options.headers['HTTP-Referer'] = 'https://coffeeclaw.app';
        options.headers['X-Title'] = 'CoffeeClaw';
      }
      req = https.request(options, function(res) {
        var data;
        data = '';
        res.on('data', function(chunk) {
          return data += chunk;
        });
        return res.on('end', function() {
          var choice, e, funcArgs, funcName, funcResult, ref, result, toolCall;
          try {
            result = JSON.parse(data);
            if (result.error) {
              return reject(new Error(result.error.message || 'API error'));
            } else if (result.choices && result.choices[0]) {
              choice = result.choices[0];
              if ((ref = choice.message) != null ? ref.tool_calls : void 0) {
                toolCall = choice.message.tool_calls[0];
                if ((toolCall != null ? toolCall.type : void 0) === 'function') {
                  funcName = toolCall.function.name;
                  funcArgs = JSON.parse(toolCall.function.arguments);
                  funcResult = executeSkillFunction(funcName, funcArgs, bot != null ? bot.skills : void 0);
                  messages.push(choice.message);
                  messages.push({
                    role: 'tool',
                    content: JSON.stringify(funcResult),
                    tool_call_id: toolCall.id
                  });
                  callAPIWithMessages(sessionId, messages, settings, bot, apiKey).then(resolve).catch(reject);
                  return;
                }
              }
              return resolve(choice.message.content);
            } else {
              return reject(new Error('Unknown response format'));
            }
          } catch (error) {
            e = error;
            return reject(e);
          }
        });
      });
      req.on('error', reject);
      req.setTimeout(60000, function() {
        req.destroy();
        return reject(new Error('Request timeout'));
      });
      req.write(postData);
      return req.end();
    });
  };

  sendToOpenClaw = async function(sessionId, message) {
    var apiKey, bot, isAgent, response, settings;
    settings = loadSettings();
    apiKey = settings.apiKey;
    if (!apiKey) {
      throw new Error('No API key configured');
    }
    bot = getActiveBot();
    isAgent = (bot != null ? bot.isAgent : void 0) || (bot != null ? bot.model : void 0) === 'openclaw-agent';
    if (isAgent) {
      addToAgentSession(sessionId, 'user', message);
      response = (await callAPI(sessionId, message, settings, bot));
      addToAgentSession(sessionId, 'assistant', response);
    } else {
      addToSession(sessionId, 'user', message);
      response = (await callAPI(sessionId, message, settings, bot));
      addToSession(sessionId, 'assistant', response);
    }
    return response;
  };

  mainWindow = null;

  createWindow = function() {
    mainWindow = new BrowserWindow({
      width: 1200,
      height: 800,
      minWidth: 800,
      minHeight: 600,
      webPreferences: {
        nodeIntegration: false,
        contextIsolation: true,
        preload: path.join(__dirname, 'preload.js')
      }
    });
    mainWindow.loadFile('index.html');
    return mainWindow.on('closed', function() {
      return mainWindow = null;
    });
  };

  app.whenReady().then(function() {
    backupSettings();
    createWindow();
    return app.on('activate', function() {
      if (BrowserWindow.getAllWindows().length === 0) {
        return createWindow();
      }
    });
  });

  app.on('before-quit', function() {
    return backupSettings();
  });

  app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
      return app.quit();
    }
  });

  ipcMain.handle('send-message', async function(event, sessionId, message) {
    var e, result;
    try {
      result = (await sendToOpenClaw(sessionId, message));
      return result;
    } catch (error) {
      e = error;
      throw e.message || e;
    }
  });

  ipcMain.handle('check-status', async function() {
    var configured, running, settings;
    running = (await checkOpenClawPromise());
    configured = isConfigured();
    settings = loadSettings();
    
    // Ensure OpenClaw config is in sync with CoffeeClaw settings
    // This handles cases where settings were modified or app was updated
    ensureOpenClawConfig();
    if (!running && configured) {
      startOpenClaw();
      return {
        running: false,
        starting: true,
        configured: true,
        hasApiKey: !!settings.apiKey
      };
    }
    return {
      running,
      starting: false,
      configured,
      hasApiKey: !!settings.apiKey
    };
  });

  ipcMain.handle('check-prerequisites', async function() {
    return {
      platform: getPlatform(),
      isWindows: isWindows,
      isMac: isMac,
      nodeInstalled: (await checkNodeInstalled()),
      npmInstalled: (await checkNpmInstalled()),
      openclawInstalled: (await checkOpenClawInstalled()),
      wslInstalled: isWindows ? (await checkWSLInstalled()) : false
    };
  });

  ipcMain.handle('has-backup', function() {
    var files;
    try {
      if (fs.existsSync(settingsFile)) {
        return false;
      }
      files = fs.readdirSync(secreteDir).filter(function(f) {
        return f.startsWith('backup.') && f.endsWith('.json');
      });
      return files.length > 0;
    } catch (error) {
      return false;
    }
  });

  ipcMain.handle('create-session', function() {
    return createSession();
  });

  ipcMain.handle('get-bots', function() {
    return loadBots();
  });

  ipcMain.handle('get-bot', function(event, botId) {
    return getBot(botId);
  });

  ipcMain.handle('get-active-bot', function() {
    return getActiveBot();
  });

  ipcMain.handle('create-bot', function(event, botConfig) {
    return createBot(botConfig);
  });

  ipcMain.handle('update-bot', function(event, botId, updates) {
    return updateBot(botId, updates);
  });

  ipcMain.handle('delete-bot', function(event, botId) {
    return deleteBot(botId);
  });

  ipcMain.handle('set-active-bot', function(event, botId) {
    return setActiveBot(botId);
  });

  ipcMain.handle('get-bot-templates', function() {
    return getBotTemplates();
  });

  ipcMain.handle('export-bots', function() {
    var botsData, e, settings;
    try {
      botsData = loadBots();
      settings = loadSettings();
      return {
        success: true,
        data: {
          bots: botsData.bots,
          activeBotId: botsData.activeBotId,
          settings: {
            token: settings.token,
            apiKey: settings.apiKey,
            provider: settings.provider,
            model: settings.model,
            feishu: settings.feishu
          },
          exportedAt: new Date().toISOString(),
          version: '1.0',
          instructions: 'To restore: Click Edit Bot button → Import → Select this file'
        }
      };
    } catch (error) {
      e = error;
      return {
        success: false,
        error: e.message
      };
    }
  });

  ipcMain.handle('import-bots', function(event, data) {
    var bot, botsData, e, existing, imported, j, len, ref, settings;
    try {
      if (!(data.bots && Array.isArray(data.bots))) {
        return {
          success: false,
          error: 'Invalid data: bots array required'
        };
      }
      botsData = loadBots();
      imported = 0;
      ref = data.bots;
      for (j = 0, len = ref.length; j < len; j++) {
        bot = ref[j];
        if (bot.id && bot.name) {
          existing = botsData.bots.find(function(b) {
            return b.id === bot.id;
          });
          if (existing) {
            Object.assign(existing, bot);
          } else {
            botsData.bots.push(bot);
          }
          imported++;
        }
      }
      saveBots(botsData);
      if (data.settings) {
        settings = loadSettings();
        if (data.settings.token) {
          settings.token = data.settings.token;
        }
        if (data.settings.apiKey) {
          settings.apiKey = data.settings.apiKey;
        }
        if (data.settings.provider) {
          settings.provider = data.settings.provider;
        }
        if (data.settings.model) {
          settings.model = data.settings.model;
        }
        if (data.settings.feishu) {
          settings.feishu = data.settings.feishu;
        }
        saveSettings(settings);
      }
      return {
        success: true,
        imported: imported,
        total: botsData.bots.length
      };
    } catch (error) {
      e = error;
      return {
        success: false,
        error: e.message
      };
    }
  });

  ipcMain.handle('backup-settings', function() {
    return backupSettings();
  });

  ipcMain.handle('list-backups', function() {
    return listSettingsBackups();
  });

  ipcMain.handle('restore-backup', function(event, backupName, options) {
    return restoreSettings(backupName, options);
  });

  ipcMain.handle('get-backup-data', function(event, backupName) {
    return getBackupData(backupName);
  });

  ipcMain.handle('export-all-settings', function() {
    return exportAllSettings();
  });

  ipcMain.handle('import-all-settings', function(event, data, options) {
    return importAllSettings(data, options);
  });

  ipcMain.handle('open-external', function(event, url) {
    return shell.openExternal(url);
  });

  ipcMain.handle('get-feishu-status', function() {
    var existing, ref, ref1, settings;
    settings = loadSettings();
    existing = detectExistingFeishuConfig();
    return {
      enabled: ((ref = settings.feishu) != null ? ref.enabled : void 0) || false,
      configured: (existing != null ? existing.enabled : void 0) || false,
      appId: ((ref1 = settings.feishu) != null ? ref1.appId : void 0) || null
    };
  });

  ipcMain.handle('sync-feishu-to-openclaw', function() {
    return syncFeishuConfigToOpenClaw();
  });

  ipcMain.handle('approve-feishu-pairing', function(event, code) {
    return new Promise(function(resolve) {
      return exec(`openclaw pairing approve feishu ${code}`, function(err, stdout, stderr) {
        if (err) {
          console.error('Error approving pairing:', err);
          return resolve({
            success: false,
            error: err.message
          });
        } else {
          console.log('Pairing approved:', stdout);
          return resolve({
            success: true,
            output: stdout
          });
        }
      });
    });
  });

  ipcMain.handle('get-session', function(event, sessionId) {
    return getSession(sessionId);
  });

  ipcMain.handle('list-sessions', function() {
    return listSessions();
  });

  ipcMain.handle('delete-session', function(event, sessionId) {
    deleteSession(sessionId);
    return true;
  });

  ipcMain.handle('get-agent-session', function(event, sessionId) {
    return getAgentSession(sessionId);
  });

  ipcMain.handle('list-agent-sessions', function() {
    return loadAgentSessions();
  });

  ipcMain.handle('get-history', function() {
    return listSessions();
  });

  ipcMain.handle('clear-history', function() {
    var key, sessions;
    sessions = loadSessions();
    for (key in sessions) {
      delete sessions[key];
    }
    saveSessions(sessions);
    return true;
  });

  ipcMain.handle('run-setup', async function(event, apiKey) {
    var e, installed, result, started, token;
    result = {
      installing: false,
      configuring: false,
      starting: false
    };
    installed = (await checkOpenClawInstalled());
    if (!installed) {
      result.installing = true;
      try {
        await installOpenClaw();
      } catch (error) {
        e = error;
        throw new Error('Failed to install OpenClaw: ' + e.message);
      }
    }
    result.configuring = true;
    token = createDefaultConfig(apiKey);
    result.starting = true;
    started = (await startOpenClaw());
    if (!started) {
      throw new Error('Failed to start OpenClaw gateway');
    }
    return result;
  });

  ipcMain.handle('get-settings', function() {
    return loadSettings();
  });

  // Mapping from CoffeeClaw provider names to OpenClaw provider names
  // CoffeeClaw uses: zhipu, openrouter, openai, deepseek
  // OpenClaw uses: glm, openrouter, openai, deepseek (same except zhipu→glm)
  PROVIDER_NAME_MAP = {
    zhipu: 'glm',
    openrouter: 'openrouter',
    openai: 'openai',
    deepseek: 'deepseek'
  };

  // Get the OpenClaw-compatible provider config from MODELS
  getOpenClawProviderConfig = function(providerId, apiKey) {
    var modelConfig, providerConfig;
    modelConfig = MODELS[providerId];
    if (!modelConfig) {
      return null;
    }
    
    // Build the provider config that OpenClaw expects
    providerConfig = {
      baseUrl: `https://${modelConfig.baseUrl}${modelConfig.apiPath}`.replace('/chat/completions', ''),
      apiKey: apiKey,
      api: 'openai-completions',
      models: modelConfig.models.map(function(m) {
        return {
          id: m.id,
          name: m.name
        };
      })
    };
    
    // Special handling for zhipu (glm) - use full API path
    if (providerId === 'zhipu') {
      providerConfig.baseUrl = "https://open.bigmodel.cn/api/paas/v4";
    }
    return providerConfig;
  };

  // Backup OpenClaw config before modifying
  // Creates a timestamped backup in the same directory
  backupOpenClawConfig = function() {
    var backupPath, backups, e, j, len, oldBackup, ref, results1, timestamp;
    if (!configExists()) {
      return;
    }
    try {
      timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      backupPath = `${configFile}.backup.${timestamp}`;
      fs.copyFileSync(configFile, backupPath);
      console.log(`Backed up OpenClaw config to: ${backupPath}`);
      
      // Keep only last 5 backups
      backups = fs.readdirSync(path.dirname(configFile)).filter(function(f) {
        return f.startsWith('openclaw.json.backup.');
      }).sort().reverse();
      ref = backups.slice(5);
      results1 = [];
      for (j = 0, len = ref.length; j < len; j++) {
        oldBackup = ref[j];
        fs.unlinkSync(path.join(path.dirname(configFile), oldBackup));
        results1.push(console.log(`Cleaned up old backup: ${oldBackup}`));
      }
      return results1;
    } catch (error) {
      e = error;
      return console.error('Failed to backup OpenClaw config:', e);
    }
  };

  // Sync providers from CoffeeClaw settings to OpenClaw's config file
  // This ensures the OpenClaw agent uses the same API keys as the CoffeeClaw UI
  // Returns true if sync was performed, false otherwise
  syncProvidersToOpenClaw = function(providers, activeProvider) {
    var base, base1, base2, base3, config, currentPrimary, e, existing, existingConfig, modelId, needsSync, newPrimary, openClawConfig, openClawProvider, openClawProviderName, providerData, providerId, ref, ref1, ref2, ref3;
    if (!configExists()) {
      return false;
    }
    if (!providers) {
      return false;
    }
    try {
      
      // Check if there's actually something to sync
      existingConfig = JSON.parse(fs.readFileSync(configFile, 'utf8'));
      if (existingConfig.models == null) {
        existingConfig.models = {};
      }
      if ((base = existingConfig.models).providers == null) {
        base.providers = {};
      }
      
      // Check if any provider actually changed OR if active provider changed
      needsSync = false;
      for (providerId in providers) {
        providerData = providers[providerId];
        openClawProviderName = PROVIDER_NAME_MAP[providerId];
        if (!openClawProviderName) {
          continue;
        }
        existing = existingConfig.models.providers[openClawProviderName];
        if (!existing || existing.apiKey !== providerData.apiKey) {
          needsSync = true;
          break;
        }
      }
      
      // Also check if active provider changed
      if (activeProvider) {
        openClawProviderName = PROVIDER_NAME_MAP[activeProvider];
        if (openClawProviderName) {
          currentPrimary = (ref = existingConfig.agents) != null ? (ref1 = ref.defaults) != null ? (ref2 = ref1.model) != null ? ref2.primary : void 0 : void 0 : void 0;
          newPrimary = `${openClawProviderName}/${(ref3 = providers[activeProvider]) != null ? ref3.model : void 0}`;
          if (currentPrimary !== newPrimary) {
            needsSync = true;
          }
        }
      }
      if (!needsSync) {
        return false;
      }
      
      // Backup before writing
      backupOpenClawConfig();
      
      // Perform the sync
      config = existingConfig;
      if (config.models == null) {
        config.models = {};
      }
      if ((base1 = config.models).providers == null) {
        base1.providers = {};
      }
      for (providerId in providers) {
        providerData = providers[providerId];
        openClawProviderName = PROVIDER_NAME_MAP[providerId];
        if (!openClawProviderName) {
          continue;
        }
        openClawConfig = getOpenClawProviderConfig(providerId, providerData.apiKey);
        if (!openClawConfig) {
          continue;
        }
        config.models.providers[openClawProviderName] = openClawConfig;
        console.log(`Synced provider ${providerId} → ${openClawProviderName} to openclaw.json`);
      }
      
      // Update primary model to match active provider
      // Note: OpenClaw uses agents.defaults.model.primary, format: "provider/modelId"
      // e.g., "glm/GLM-4-Flash" or "openrouter/auto"
      if (providers && activeProvider && PROVIDER_NAME_MAP[activeProvider]) {
        openClawProvider = PROVIDER_NAME_MAP[activeProvider];
        providerData = providers[activeProvider];
        if (providerData && providerData.model) {
          // For openrouter models, the id might be "openrouter/auto" so we use it directly
          // For others like glm, it's "glm-4-flash" so we format as "provider/model"
          modelId = providerData.model;
          if (!modelId.startsWith(openClawProvider)) {
            modelId = `${openClawProvider}/${modelId}`;
          }
          if (config.agents == null) {
            config.agents = {};
          }
          if ((base2 = config.agents).defaults == null) {
            base2.defaults = {};
          }
          if ((base3 = config.agents.defaults).model == null) {
            base3.model = {};
          }
          config.agents.defaults.model.primary = modelId;
          console.log(`Set primary model to: ${modelId}`);
        }
      }
      fs.writeFileSync(configFile, JSON.stringify(config, null, 2));
      console.log('Providers synced to OpenClaw config');
      return true;
    } catch (error) {
      e = error;
      console.error('Failed to sync providers to OpenClaw:', e);
      return false;
    }
  };

  // Ensure OpenClaw config is in sync with CoffeeClaw settings
  // Only syncs if CoffeeClaw settings are newer than OpenClaw config
  // Called at startup to handle cases where settings were modified outside the app
  ensureOpenClawConfig = function() {
    var e, openclawConfigMtime, settings, settingsMtime;
    settings = loadSettings();
    if (!settings.providers) {
      return;
    }
    if (!configExists()) {
      return;
    }
    if (!fs.existsSync(settingsFile)) {
      return;
    }
    try {
      openclawConfigMtime = fs.statSync(configFile).mtime.getTime();
      settingsMtime = fs.statSync(settingsFile).mtime.getTime();
      if (settingsMtime > openclawConfigMtime) {
        console.log('CoffeeClaw settings are newer than OpenClaw config, syncing...');
        return syncProvidersToOpenClaw(settings.providers, settings.activeProvider);
      }
    } catch (error) {
      e = error;
      return console.error('Failed to ensure OpenClaw config:', e);
    }
  };

  ipcMain.handle('save-settings', function(event, newSettings) {
    var activeProvider, key, settings, value;
    settings = loadSettings();
    for (key in newSettings) {
      value = newSettings[key];
      settings[key] = value;
    }
    saveSettings(settings);
    
    // When providers are saved in CoffeeClaw settings, also sync them to OpenClaw's config
    // This ensures the OpenClaw agent uses the same API keys configured in the UI
    if (newSettings.providers) {
      activeProvider = newSettings.activeProvider || settings.activeProvider;
      syncProvidersToOpenClaw(newSettings.providers, activeProvider);
    }
    return true;
  });

  ipcMain.handle('get-license', function() {
    return getLicenseStatus();
  });

  ipcMain.handle('get-license-prices', function() {
    return LICENSE_PRICES;
  });

  ipcMain.handle('activate-license', function(event, plan, paymentInfo) {
    var license;
    license = loadLicense();
    if (!license) {
      license = initLicense();
    }
    license.paid = true;
    license.plan = plan;
    license.activatedAt = new Date().toISOString();
    if (plan === 'lifetime') {
      license.showIndicator = false;
    } else if (plan === 'yearly') {
      license.balance = (license.balance || 0) + 12;
    } else if (plan === 'monthly') {
      license.balance = (license.balance || 0) + 1;
    }
    license.paymentInfo = paymentInfo;
    saveLicense(license);
    return getLicenseStatus();
  });

  ipcMain.handle('add-payment', function(event, paymentData) {
    var amount, currency, e, email, license, lifetimeThreshold, method;
    try {
      license = loadLicense();
      if (!license) {
        license = initLicense();
      }
      ({amount, method, email, currency} = paymentData);
      if (!(amount && amount > 0)) {
        return {
          success: false,
          error: 'Invalid amount'
        };
      }
      currency = currency || 'usd';
      if (!license.currency) {
        license.currency = currency;
      }
      if (license.currency !== currency) {
        return {
          success: false,
          error: `Currency mismatch. Your account uses ${license.currency}`
        };
      }
      license.balance = (license.balance || 0) + amount;
      license.paid = true;
      lifetimeThreshold = currency === 'cny' ? 216 : 36;
      if (amount >= lifetimeThreshold) {
        license.plan = 'lifetime';
      }
      license.paymentInfo = license.paymentInfo || [];
      license.paymentInfo.push({
        amount: amount,
        method: method,
        email: email,
        currency: currency,
        timestamp: new Date().toISOString()
      });
      saveLicense(license);
      return {
        success: true,
        balance: license.balance
      };
    } catch (error) {
      e = error;
      console.error('Error adding payment:', e);
      return {
        success: false,
        error: e.message
      };
    }
  });

  ipcMain.handle('get-models', function() {
    return MODELS;
  });

  detectExistingFeishuConfig = function() {
    var config, e, feishuChannel, ref, ref1, ref2;
    try {
      if (fs.existsSync(configFile)) {
        config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
        if ((ref = config.channels) != null ? (ref1 = ref.feishu) != null ? ref1.enabled : void 0 : void 0) {
          feishuChannel = config.channels.feishu;
          if (feishuChannel.appId) {
            return {
              enabled: true,
              appId: feishuChannel.appId,
              appSecret: feishuChannel.appSecret,
              botName: feishuChannel.botName || 'CoffeeClaw',
              detected: true
            };
          } else if ((ref2 = feishuChannel.accounts) != null ? ref2.main : void 0) {
            return {
              enabled: true,
              appId: feishuChannel.accounts.main.appId,
              appSecret: feishuChannel.accounts.main.appSecret,
              botName: feishuChannel.accounts.main.botName || 'CoffeeClaw',
              detected: true
            };
          }
        }
      }
    } catch (error) {
      e = error;
      console.error('Error detecting Feishu config:', e);
    }
    return null;
  };

  syncFeishuConfigToSettings = function() {
    var existing, ref, settings;
    existing = detectExistingFeishuConfig();
    if (existing) {
      settings = loadSettings();
      if (!((ref = settings.feishu) != null ? ref.appId : void 0)) {
        settings.feishu = existing;
        saveSettings(settings);
        console.log('Synced existing Feishu config to settings');
      }
      return existing;
    }
    return null;
  };

  syncFeishuConfigToOpenClaw = function() {
    var base, base1, config, e, existing, ref, ref1, ref2, ref3, ref4, ref5, settings;
    settings = loadSettings();
    if (!((ref = settings.feishu) != null ? ref.appId : void 0) || !((ref1 = settings.feishu) != null ? ref1.enabled : void 0)) {
      return false;
    }
    existing = detectExistingFeishuConfig();
    if (existing != null ? existing.enabled : void 0) {
      return true;
    }
    try {
      config = {};
      if (fs.existsSync(configFile)) {
        config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
      }
      if (((ref2 = config.channels) != null ? (ref3 = ref2.feishu) != null ? ref3.enabled : void 0 : void 0) && ((ref4 = config.channels) != null ? (ref5 = ref4.feishu) != null ? ref5.appId : void 0 : void 0)) {
        return true;
      }
      if (config.channels == null) {
        config.channels = {};
      }
      config.channels.feishu = {
        enabled: true,
        appId: settings.feishu.appId,
        appSecret: settings.feishu.appSecret,
        domain: 'feishu',
        dmPolicy: settings.feishu.dmPolicy || 'pairing',
        groupPolicy: settings.feishu.groupPolicy || 'open'
      };
      if (config.plugins == null) {
        config.plugins = {};
      }
      if ((base = config.plugins).entries == null) {
        base.entries = {};
      }
      config.plugins.entries.feishu = {
        enabled: true
      };
      if (settings.apiKey) {
        if (config.models == null) {
          config.models = {};
        }
        if ((base1 = config.models).providers == null) {
          base1.providers = {};
        }
        config.models.providers.glm = {
          baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
          apiKey: settings.apiKey,
          api: 'openai-completions',
          models: [
            {
              id: 'GLM-4-Flash',
              name: 'GLM 4 Flash'
            },
            {
              id: 'GLM-4.5-air',
              name: 'GLM 4.5 Air'
            },
            {
              id: 'GLM-4.7',
              name: 'GLM 4.7'
            }
          ]
        };
      }
      fs.writeFileSync(configFile, JSON.stringify(config, null, 2));
      console.log('Synced Feishu config to OpenClaw');
      return true;
    } catch (error) {
      e = error;
      console.error('Error syncing Feishu to OpenClaw:', e);
      return false;
    }
  };

  configureFeishu = function(appId, appSecret, botName, enabled = true) {
    var base, config, settings;
    settings = loadSettings();
    settings.feishu = {
      appId: appId,
      appSecret: appSecret,
      botName: botName || 'CoffeeClaw',
      enabled: enabled
    };
    saveSettings(settings);
    if (configExists()) {
      config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
      if (config.plugins == null) {
        config.plugins = {};
      }
      config.plugins.feishu = {
        enabled: enabled
      };
      if (config.channels == null) {
        config.channels = {};
      }
      config.channels.feishu = {
        enabled: enabled,
        dmPolicy: 'pairing',
        accounts: {
          main: {
            appId: appId,
            appSecret: appSecret,
            botName: botName || 'CoffeeClaw'
          }
        }
      };
      if (settings.apiKey) {
        if (config.models == null) {
          config.models = {};
        }
        if ((base = config.models).providers == null) {
          base.providers = {};
        }
        config.models.providers.glm = {
          baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
          apiKey: settings.apiKey,
          api: 'openai-completions',
          models: [
            {
              id: 'GLM-4-Flash',
              name: 'GLM 4 Flash'
            },
            {
              id: 'GLM-4.5-air',
              name: 'GLM 4.5 Air'
            },
            {
              id: 'GLM-4.7',
              name: 'GLM 4.7'
            }
          ]
        };
      }
      fs.writeFileSync(configFile, JSON.stringify(config, null, 2));
    }
    return {
      success: true
    };
  };

  ipcMain.handle('call-openclaw-agent', async function(event, sessionId, message) {
    var e, result;
    try {
      result = (await callOpenClawAgent(sessionId, message));
      return result;
    } catch (error) {
      e = error;
      throw e.message || e;
    }
  });

}).call(this);
