// Generated by CoffeeScript 2.7.0
(function() {
  // CoffeeClaw - Main Process
  // Auto-configures OpenClaw on first run
  var BrowserWindow, MAX_HISTORY, addToHistory, agentDir, agentMdFile, agentModelsFile, app, callZhipuAPI, checkOpenClaw, checkOpenClawInstalled, checkOpenClawPromise, clearHistory, configExists, configFile, createAgentConfig, createDefaultConfig, createIdentity, createWindow, crypto, exec, fs, generateToken, historyFile, http, https, identityFile, installOpenClaw, ipcMain, isConfigured, loadHistory, loadSettings, mainWindow, openclawDir, path, saveHistory, saveSettings, secreteDir, sendToOpenClaw, settingsFile, spawn, startOpenClaw, workspaceDir;

  ({app, BrowserWindow, ipcMain} = require('electron'));

  path = require('path');

  fs = require('fs');

  http = require('http');

  https = require('https');

  ({exec, spawn} = require('child_process'));

  crypto = require('crypto');

  openclawDir = path.join(process.env.HOME, '.openclaw');

  configFile = path.join(openclawDir, 'openclaw.json');

  workspaceDir = path.join(openclawDir, 'workspace');

  identityFile = path.join(workspaceDir, 'IDENTITY.md');

  agentDir = path.join(openclawDir, 'agents', 'main', 'agent');

  agentMdFile = path.join(agentDir, 'agent.md');

  agentModelsFile = path.join(agentDir, 'models.json');

  secreteDir = path.join(path.dirname(__dirname), '.secrete');

  settingsFile = path.join(secreteDir, 'settings.json');

  historyFile = path.join(secreteDir, 'history.json');

  MAX_HISTORY = 100;

  generateToken = function() {
    return crypto.randomBytes(24).toString('hex');
  };

  loadSettings = function() {
    var data, e, settings;
    try {
      if (fs.existsSync(settingsFile)) {
        data = fs.readFileSync(settingsFile, 'utf8');
        settings = JSON.parse(data);
        if (settings.token && settings.apiKey) {
          return settings;
        }
      }
    } catch (error) {
      e = error;
      console.error('Error loading settings:', e);
    }
    return {};
  };

  saveSettings = function(settings) {
    var e;
    try {
      fs.mkdirSync(secreteDir, {
        recursive: true
      });
      return fs.writeFileSync(settingsFile, JSON.stringify(settings, null, 2));
    } catch (error) {
      e = error;
      return console.error('Error saving settings:', e);
    }
  };

  loadHistory = function() {
    var data, e;
    try {
      if (fs.existsSync(historyFile)) {
        data = fs.readFileSync(historyFile, 'utf8');
        return JSON.parse(data);
      }
    } catch (error) {
      e = error;
      console.error('Error loading history:', e);
    }
    return [];
  };

  saveHistory = function(history) {
    var e, trimmed;
    try {
      fs.mkdirSync(secreteDir, {
        recursive: true
      });
      trimmed = history.slice(-MAX_HISTORY);
      return fs.writeFileSync(historyFile, JSON.stringify(trimmed, null, 2));
    } catch (error) {
      e = error;
      return console.error('Error saving history:', e);
    }
  };

  addToHistory = function(role, content) {
    var history;
    history = loadHistory();
    history.push({
      role: role,
      content: content,
      timestamp: Date.now()
    });
    saveHistory(history);
    return history;
  };

  clearHistory = function() {
    return saveHistory([]);
  };

  checkOpenClaw = function(callback) {
    var req;
    req = http.get('http://127.0.0.1:18789/health', function(res) {
      return callback(true);
    });
    req.on('error', function() {
      return callback(false);
    });
    return req.setTimeout(2000, function() {
      req.destroy();
      return callback(false);
    });
  };

  checkOpenClawPromise = function() {
    return new Promise(function(resolve) {
      return checkOpenClaw(resolve);
    });
  };

  startOpenClaw = function() {
    return new Promise(function(resolve) {
      var attempts, check, child, maxAttempts;
      console.log('Starting OpenClaw gateway...');
      child = spawn('openclaw', ['gateway', '--dev'], {
        detached: true,
        stdio: 'ignore'
      });
      child.unref();
      attempts = 0;
      maxAttempts = 30;
      check = function() {
        attempts++;
        return checkOpenClaw(function(running) {
          if (running) {
            return resolve(true);
          } else if (attempts < maxAttempts) {
            return setTimeout(check, 1000);
          } else {
            return resolve(false);
          }
        });
      };
      return setTimeout(check, 2000);
    });
  };

  configExists = function() {
    try {
      return fs.existsSync(configFile);
    } catch (error) {
      return false;
    }
  };

  isConfigured = function() {
    var settings;
    settings = loadSettings();
    return settings.token && settings.apiKey;
  };

  createDefaultConfig = function(apiKey) {
    var defaultConfig, key, settings, token;
    console.log('Creating OpenClaw config...');
    settings = loadSettings();
    token = settings.token || generateToken();
    key = apiKey || settings.apiKey || '';
    if (!fs.existsSync(openclawDir)) {
      fs.mkdirSync(openclawDir, {
        recursive: true
      });
    }
    if (!fs.existsSync(workspaceDir)) {
      fs.mkdirSync(workspaceDir, {
        recursive: true
      });
    }
    if (!fs.existsSync(agentDir)) {
      fs.mkdirSync(agentDir, {
        recursive: true
      });
    }
    defaultConfig = {
      meta: {
        lastTouchedVersion: '2026.3.2',
        lastTouchedAt: new Date().toISOString()
      },
      env: {},
      models: {
        providers: {}
      },
      agents: {
        defaults: {
          model: {
            primary: 'glm/GLM-4-Flash'
          },
          models: {
            'glm/GLM-4-Flash': {}
          },
          compaction: {
            mode: 'safeguard'
          }
        }
      },
      commands: {
        native: 'auto',
        nativeSkills: 'auto',
        restart: true,
        ownerDisplay: 'raw'
      },
      channels: {
        feishu: {
          enabled: false
        }
      },
      gateway: {
        mode: 'local',
        http: {
          endpoints: {
            chatCompletions: {
              enabled: true
            }
          }
        },
        auth: {
          mode: 'token',
          token: token
        }
      }
    };
    if (key) {
      defaultConfig.env.ZHIPU_API_KEY = key;
      defaultConfig.models.providers.glm = {
        baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
        apiKey: key,
        api: 'openai-completions',
        models: [
          {
            id: 'GLM-4-Flash',
            name: 'GLM 4 Flash'
          },
          {
            id: 'GLM-4.5-air',
            name: 'GLM 4.5 air'
          },
          {
            id: 'GLM-4.7',
            name: 'GLM 4.7'
          }
        ]
      };
    }
    fs.writeFileSync(configFile, JSON.stringify(defaultConfig, null, 2));
    console.log('Config created at:', configFile);
    settings.token = token;
    if (key) {
      settings.apiKey = key;
    }
    saveSettings(settings);
    createIdentity();
    createAgentConfig(key);
    return token;
  };

  createIdentity = function() {
    var identity;
    if (fs.existsSync(identityFile)) {
      return;
    }
    console.log('Creating identity...');
    identity = `# IDENTITY.md - Who Am I?

- **Name:** CoffeeClaw
- **Creature:** AI Assistant
- **Vibe:** helpful and friendly
- **Emoji:** ☕

I am a desktop AI assistant powered by OpenClaw and Zhipu GLM models.
I can help you with various tasks and answer your questions.`;
    fs.writeFileSync(identityFile, identity);
    return console.log('Identity created at:', identityFile);
  };

  createAgentConfig = function(apiKey) {
    var agentMd, agentModels, key;
    key = apiKey || '';
    agentModels = {
      providers: {}
    };
    if (key) {
      agentModels.providers.glm = {
        baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
        apiKey: key,
        api: 'openai-completions',
        models: [
          {
            id: 'GLM-4-Flash',
            name: 'GLM 4 Flash',
            reasoning: false,
            input: ['text'],
            cost: {
              input: 0,
              output: 0,
              cacheRead: 0,
              cacheWrite: 0
            },
            contextWindow: 200000,
            maxTokens: 8192,
            api: 'openai-completions'
          }
        ]
      };
    }
    fs.writeFileSync(agentModelsFile, JSON.stringify(agentModels, null, 2));
    agentMd = `# Agent Configuration

## Identity
You are a helpful AI assistant running on the user's local machine. You are powered by GLM-4-Flash model from Zhipu AI.

## Capabilities
- File system access (sandboxed)
- System command execution (limited)
- Answer questions and provide assistance

## Safety Rules
- Confirm destructive actions
- Respect user privacy
- Be helpful and concise

## Communication
- Respond in the same language the user uses
- Be friendly and professional
- Provide clear and accurate information`;
    fs.writeFileSync(agentMdFile, agentMd);
    return console.log('Agent config created');
  };

  checkOpenClawInstalled = function() {
    return new Promise(function(resolve) {
      return exec('which openclaw', function(err) {
        return resolve(!err);
      });
    });
  };

  installOpenClaw = function() {
    return new Promise(function(resolve, reject) {
      console.log('Installing OpenClaw...');
      return exec('npm install -g openclaw', function(err, stdout, stderr) {
        if (err) {
          console.error('Install error:', stderr);
          return reject(err);
        } else {
          console.log('OpenClaw installed successfully');
          return resolve(true);
        }
      });
    });
  };

  callZhipuAPI = function(message, apiKey) {
    return new Promise(function(resolve, reject) {
      var history, i, len, messages, msg, options, postData, req;
      history = loadHistory();
      messages = [
        {
          role: 'system',
          content: 'You are CoffeeClaw, a helpful AI assistant. Respond in the same language the user uses. Be friendly and helpful.'
        }
      ];
      for (i = 0, len = history.length; i < len; i++) {
        msg = history[i];
        messages.push({
          role: msg.role,
          content: msg.content
        });
      }
      messages.push({
        role: 'user',
        content: message
      });
      postData = JSON.stringify({
        model: 'glm-4-flash',
        messages: messages,
        stream: false
      });
      options = {
        hostname: 'open.bigmodel.cn',
        port: 443,
        path: '/api/paas/v4/chat/completions',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
          'Content-Length': Buffer.byteLength(postData)
        }
      };
      req = https.request(options, function(res) {
        var data;
        data = '';
        res.on('data', function(chunk) {
          return data += chunk;
        });
        return res.on('end', function() {
          var e, result;
          try {
            result = JSON.parse(data);
            if (result.error) {
              return reject(new Error(result.error.message || 'API error'));
            } else if (result.choices && result.choices[0]) {
              return resolve(result.choices[0].message.content);
            } else {
              return reject(new Error('Unknown response format'));
            }
          } catch (error) {
            e = error;
            return reject(e);
          }
        });
      });
      req.on('error', reject);
      req.setTimeout(60000, function() {
        req.destroy();
        return reject(new Error('Request timeout'));
      });
      req.write(postData);
      return req.end();
    });
  };

  sendToOpenClaw = async function(message) {
    var apiKey, response, settings;
    settings = loadSettings();
    apiKey = settings.apiKey;
    if (!apiKey) {
      throw new Error('No API key configured');
    }
    addToHistory('user', message);
    response = (await callZhipuAPI(message, apiKey));
    addToHistory('assistant', response);
    return response;
  };

  mainWindow = null;

  createWindow = function() {
    mainWindow = new BrowserWindow({
      width: 700,
      height: 800,
      minWidth: 500,
      minHeight: 600,
      webPreferences: {
        nodeIntegration: false,
        contextIsolation: true,
        preload: path.join(__dirname, 'preload.js')
      }
    });
    mainWindow.loadFile('index.html');
    return mainWindow.on('closed', function() {
      return mainWindow = null;
    });
  };

  app.whenReady().then(function() {
    createWindow();
    return app.on('activate', function() {
      if (BrowserWindow.getAllWindows().length === 0) {
        return createWindow();
      }
    });
  });

  app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
      return app.quit();
    }
  });

  ipcMain.handle('send-message', async function(event, message) {
    var e, result;
    try {
      result = (await sendToOpenClaw(message));
      return result;
    } catch (error) {
      e = error;
      throw e.message || e;
    }
  });

  ipcMain.handle('check-status', async function() {
    var configured, running, settings;
    running = (await checkOpenClawPromise());
    configured = isConfigured();
    settings = loadSettings();
    if (!running && configured) {
      startOpenClaw();
      return {
        running: false,
        starting: true,
        configured: true,
        hasApiKey: !!settings.apiKey
      };
    }
    return {
      running,
      starting: false,
      configured,
      hasApiKey: !!settings.apiKey
    };
  });

  ipcMain.handle('run-setup', async function(event, apiKey) {
    var e, installed, result, started, token;
    result = {
      installing: false,
      configuring: false,
      starting: false
    };
    installed = (await checkOpenClawInstalled());
    if (!installed) {
      result.installing = true;
      try {
        await installOpenClaw();
      } catch (error) {
        e = error;
        throw new Error('Failed to install OpenClaw: ' + e.message);
      }
    }
    result.configuring = true;
    token = createDefaultConfig(apiKey);
    result.starting = true;
    started = (await startOpenClaw());
    if (!started) {
      throw new Error('Failed to start OpenClaw gateway');
    }
    return result;
  });

  ipcMain.handle('get-settings', function() {
    return loadSettings();
  });

  ipcMain.handle('get-history', function() {
    return loadHistory();
  });

  ipcMain.handle('clear-history', function() {
    clearHistory();
    return true;
  });

  ipcMain.handle('save-api-key', function(event, apiKey) {
    var base, config, settings;
    settings = loadSettings();
    settings.apiKey = apiKey;
    saveSettings(settings);
    if (configExists()) {
      config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
      if (config.env == null) {
        config.env = {};
      }
      config.env.ZHIPU_API_KEY = apiKey;
      if (config.models == null) {
        config.models = {};
      }
      if ((base = config.models).providers == null) {
        base.providers = {};
      }
      config.models.providers.glm = {
        baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
        apiKey: apiKey,
        api: 'openai-completions',
        models: [
          {
            id: 'GLM-4-Flash',
            name: 'GLM 4 Flash'
          },
          {
            id: 'GLM-4.5-air',
            name: 'GLM 4.5 air'
          },
          {
            id: 'GLM-4.7',
            name: 'GLM 4.7'
          }
        ]
      };
      fs.writeFileSync(configFile, JSON.stringify(config, null, 2));
      createAgentConfig(apiKey);
    }
    return true;
  });

}).call(this);
