// Generated by CoffeeScript 2.7.0
(function() {
  // CoffeeClaw - Main Process
  // Auto-configures OpenClaw on first run
  var BrowserWindow, MAX_HISTORY, MAX_SESSIONS, MODELS, addToSession, agentDir, agentMdFile, agentModelsFile, app, callAPI, checkNodeInstalled, checkNpmInstalled, checkOpenClaw, checkOpenClawInstalled, checkOpenClawPromise, checkWSLInstalled, configExists, configFile, createAgentConfig, createDefaultConfig, createIdentity, createSession, createWindow, crypto, deleteSession, exec, fs, generateId, generateToken, getPlatform, getSession, http, https, identityFile, installOpenClaw, ipcMain, isConfigured, isMac, isWindows, listSessions, loadSessions, loadSettings, mainWindow, openclawDir, path, saveSession, saveSessions, saveSettings, secreteDir, sendToOpenClaw, sessionsFile, settingsFile, spawn, startOpenClaw, workspaceDir;

  ({app, BrowserWindow, ipcMain} = require('electron'));

  path = require('path');

  fs = require('fs');

  http = require('http');

  https = require('https');

  ({exec, spawn} = require('child_process'));

  crypto = require('crypto');

  openclawDir = path.join(process.env.HOME, '.openclaw');

  configFile = path.join(openclawDir, 'openclaw.json');

  workspaceDir = path.join(openclawDir, 'workspace');

  identityFile = path.join(workspaceDir, 'IDENTITY.md');

  agentDir = path.join(openclawDir, 'agents', 'main', 'agent');

  agentMdFile = path.join(agentDir, 'agent.md');

  agentModelsFile = path.join(agentDir, 'models.json');

  secreteDir = path.join(path.dirname(__dirname), '.secrete');

  settingsFile = path.join(secreteDir, 'settings.json');

  sessionsFile = path.join(secreteDir, 'sessions.json');

  MAX_HISTORY = 100;

  MAX_SESSIONS = 50;

  isWindows = process.platform === 'win32';

  isMac = process.platform === 'darwin';

  generateToken = function() {
    return crypto.randomBytes(24).toString('hex');
  };

  generateId = function() {
    return Date.now().toString(36) + Math.random().toString(36).substr(2, 9);
  };

  loadSettings = function() {
    var data, e, settings;
    try {
      if (fs.existsSync(settingsFile)) {
        data = fs.readFileSync(settingsFile, 'utf8');
        settings = JSON.parse(data);
        if (settings.token && settings.apiKey) {
          return settings;
        }
      }
    } catch (error) {
      e = error;
      console.error('Error loading settings:', e);
    }
    return {};
  };

  saveSettings = function(settings) {
    var e;
    try {
      fs.mkdirSync(secreteDir, {
        recursive: true
      });
      return fs.writeFileSync(settingsFile, JSON.stringify(settings, null, 2));
    } catch (error) {
      e = error;
      return console.error('Error saving settings:', e);
    }
  };

  loadSessions = function() {
    var data, e;
    try {
      if (fs.existsSync(sessionsFile)) {
        data = fs.readFileSync(sessionsFile, 'utf8');
        return JSON.parse(data);
      }
    } catch (error) {
      e = error;
      console.error('Error loading sessions:', e);
    }
    return {};
  };

  saveSessions = function(sessions) {
    var e;
    try {
      fs.mkdirSync(secreteDir, {
        recursive: true
      });
      return fs.writeFileSync(sessionsFile, JSON.stringify(sessions, null, 2));
    } catch (error) {
      e = error;
      return console.error('Error saving sessions:', e);
    }
  };

  getSession = function(sessionId) {
    var sessions;
    sessions = loadSessions();
    return sessions[sessionId] || {
      id: sessionId,
      messages: [],
      createdAt: Date.now()
    };
  };

  saveSession = function(sessionId, session) {
    var oldest, sessionIds, sessions;
    sessions = loadSessions();
    session.messages = session.messages.slice(-MAX_HISTORY);
    sessions[sessionId] = session;
    sessionIds = Object.keys(sessions);
    if (sessionIds.length > MAX_SESSIONS) {
      oldest = sessionIds.sort(function(a, b) {
        return sessions[a].createdAt - sessions[b].createdAt;
      })[0];
      delete sessions[oldest];
    }
    return saveSessions(sessions);
  };

  addToSession = function(sessionId, role, content) {
    var session;
    session = getSession(sessionId);
    if (!session.messages) {
      session.messages = [];
    }
    session.messages.push({
      role: role,
      content: content,
      timestamp: Date.now()
    });
    if (!session.title && role === 'user') {
      session.title = content.substring(0, 50);
    }
    if (!session.createdAt) {
      session.createdAt = Date.now();
    }
    session.updatedAt = Date.now();
    saveSession(sessionId, session);
    return session;
  };

  createSession = function() {
    var session, sessionId;
    sessionId = generateId();
    session = {
      id: sessionId,
      title: '',
      messages: [],
      createdAt: Date.now(),
      updatedAt: Date.now()
    };
    saveSession(sessionId, session);
    return session;
  };

  deleteSession = function(sessionId) {
    var sessions;
    sessions = loadSessions();
    delete sessions[sessionId];
    return saveSessions(sessions);
  };

  listSessions = function() {
    var key, result, session, sessions;
    sessions = loadSessions();
    result = [];
    for (key in sessions) {
      session = sessions[key];
      result.push(session);
    }
    result.sort(function(a, b) {
      return (b.updatedAt || 0) - (a.updatedAt || 0);
    });
    return result;
  };

  checkOpenClaw = function(callback) {
    var req;
    req = http.get('http://127.0.0.1:18789/health', function(res) {
      return callback(true);
    });
    req.on('error', function() {
      return callback(false);
    });
    return req.setTimeout(2000, function() {
      req.destroy();
      return callback(false);
    });
  };

  checkOpenClawPromise = function() {
    return new Promise(function(resolve) {
      return checkOpenClaw(resolve);
    });
  };

  startOpenClaw = function() {
    return new Promise(function(resolve) {
      var attempts, check, child, maxAttempts;
      console.log('Starting OpenClaw gateway...');
      child = spawn('openclaw', ['gateway', '--dev'], {
        detached: true,
        stdio: 'ignore'
      });
      child.unref();
      attempts = 0;
      maxAttempts = 30;
      check = function() {
        attempts++;
        return checkOpenClaw(function(running) {
          if (running) {
            return resolve(true);
          } else if (attempts < maxAttempts) {
            return setTimeout(check, 1000);
          } else {
            return resolve(false);
          }
        });
      };
      return setTimeout(check, 2000);
    });
  };

  configExists = function() {
    try {
      return fs.existsSync(configFile);
    } catch (error) {
      return false;
    }
  };

  isConfigured = function() {
    var settings;
    settings = loadSettings();
    return settings.token && settings.apiKey;
  };

  createDefaultConfig = function(apiKey) {
    var defaultConfig, key, settings, token;
    console.log('Creating OpenClaw config...');
    settings = loadSettings();
    token = settings.token || generateToken();
    key = apiKey || settings.apiKey || '';
    if (!fs.existsSync(openclawDir)) {
      fs.mkdirSync(openclawDir, {
        recursive: true
      });
    }
    if (!fs.existsSync(workspaceDir)) {
      fs.mkdirSync(workspaceDir, {
        recursive: true
      });
    }
    if (!fs.existsSync(agentDir)) {
      fs.mkdirSync(agentDir, {
        recursive: true
      });
    }
    defaultConfig = {
      meta: {
        lastTouchedVersion: '2026.3.2',
        lastTouchedAt: new Date().toISOString()
      },
      env: {},
      models: {
        providers: {}
      },
      agents: {
        defaults: {
          model: {
            primary: 'glm/GLM-4-Flash'
          },
          models: {
            'glm/GLM-4-Flash': {}
          },
          compaction: {
            mode: 'safeguard'
          }
        }
      },
      commands: {
        native: 'auto',
        nativeSkills: 'auto',
        restart: true,
        ownerDisplay: 'raw'
      },
      channels: {
        feishu: {
          enabled: false
        }
      },
      gateway: {
        mode: 'local',
        http: {
          endpoints: {
            chatCompletions: {
              enabled: true
            }
          }
        },
        auth: {
          mode: 'token',
          token: token
        }
      }
    };
    if (key) {
      defaultConfig.env.ZHIPU_API_KEY = key;
      defaultConfig.models.providers.glm = {
        baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
        apiKey: key,
        api: 'openai-completions',
        models: [
          {
            id: 'GLM-4-Flash',
            name: 'GLM 4 Flash'
          },
          {
            id: 'GLM-4.5-air',
            name: 'GLM 4.5 air'
          },
          {
            id: 'GLM-4.7',
            name: 'GLM 4.7'
          }
        ]
      };
    }
    fs.writeFileSync(configFile, JSON.stringify(defaultConfig, null, 2));
    console.log('Config created at:', configFile);
    settings.token = token;
    if (key) {
      settings.apiKey = key;
    }
    saveSettings(settings);
    createIdentity();
    createAgentConfig(key);
    return token;
  };

  createIdentity = function() {
    var identity;
    if (fs.existsSync(identityFile)) {
      return;
    }
    console.log('Creating identity...');
    identity = `# IDENTITY.md - Who Am I?

- **Name:** CoffeeClaw
- **Creature:** AI Assistant
- **Vibe:** helpful and friendly
- **Emoji:** ☕

I am a desktop AI assistant powered by OpenClaw and Zhipu GLM models.
I can help you with various tasks and answer your questions.`;
    fs.writeFileSync(identityFile, identity);
    return console.log('Identity created at:', identityFile);
  };

  createAgentConfig = function(apiKey) {
    var agentMd, agentModels, key;
    key = apiKey || '';
    agentModels = {
      providers: {}
    };
    if (key) {
      agentModels.providers.glm = {
        baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
        apiKey: key,
        api: 'openai-completions',
        models: [
          {
            id: 'GLM-4-Flash',
            name: 'GLM 4 Flash',
            reasoning: false,
            input: ['text'],
            cost: {
              input: 0,
              output: 0,
              cacheRead: 0,
              cacheWrite: 0
            },
            contextWindow: 200000,
            maxTokens: 8192,
            api: 'openai-completions'
          }
        ]
      };
    }
    fs.writeFileSync(agentModelsFile, JSON.stringify(agentModels, null, 2));
    agentMd = `# Agent Configuration

## Identity
You are a helpful AI assistant running on the user's local machine. You are powered by GLM-4-Flash model from Zhipu AI.

## Capabilities
- File system access (sandboxed)
- System command execution (limited)
- Answer questions and provide assistance

## Safety Rules
- Confirm destructive actions
- Respect user privacy
- Be helpful and concise

## Communication
- Respond in the same language the user uses
- Be friendly and professional
- Provide clear and accurate information`;
    fs.writeFileSync(agentMdFile, agentMd);
    return console.log('Agent config created');
  };

  checkOpenClawInstalled = function() {
    return new Promise(function(resolve) {
      var cmd;
      cmd = isWindows ? 'where openclaw' : 'which openclaw';
      return exec(cmd, function(err) {
        return resolve(!err);
      });
    });
  };

  checkNodeInstalled = function() {
    return new Promise(function(resolve) {
      return exec('node --version', function(err, stdout) {
        return resolve(!err);
      });
    });
  };

  checkNpmInstalled = function() {
    return new Promise(function(resolve) {
      return exec('npm --version', function(err, stdout) {
        return resolve(!err);
      });
    });
  };

  checkWSLInstalled = function() {
    return new Promise(function(resolve) {
      return exec('wsl --list', function(err, stdout) {
        return resolve(!err);
      });
    });
  };

  getPlatform = function() {
    return process.platform;
  };

  installOpenClaw = function() {
    return new Promise(function(resolve, reject) {
      console.log('Installing OpenClaw...');
      return exec('npm install -g openclaw', function(err, stdout, stderr) {
        if (err) {
          console.error('Install error:', stderr);
          return reject(err);
        } else {
          console.log('OpenClaw installed successfully');
          return resolve(true);
        }
      });
    });
  };

  MODELS = {
    zhipu: {
      name: 'Zhipu GLM',
      models: [
        {
          id: 'glm-4-flash',
          name: 'GLM-4-Flash (Free)',
          free: true
        },
        {
          id: 'glm-4-plus',
          name: 'GLM-4-Plus'
        },
        {
          id: 'glm-4-air',
          name: 'GLM-4-Air'
        }
      ],
      baseUrl: 'open.bigmodel.cn',
      apiPath: '/api/paas/v4/chat/completions'
    },
    openai: {
      name: 'OpenAI',
      models: [
        {
          id: 'gpt-4o-mini',
          name: 'GPT-4o Mini'
        },
        {
          id: 'gpt-4o',
          name: 'GPT-4o'
        },
        {
          id: 'gpt-4-turbo',
          name: 'GPT-4 Turbo'
        }
      ],
      baseUrl: 'api.openai.com',
      apiPath: '/v1/chat/completions'
    },
    deepseek: {
      name: 'DeepSeek',
      models: [
        {
          id: 'deepseek-chat',
          name: 'DeepSeek Chat'
        },
        {
          id: 'deepseek-coder',
          name: 'DeepSeek Coder'
        }
      ],
      baseUrl: 'api.deepseek.com',
      apiPath: '/v1/chat/completions'
    }
  };

  callAPI = function(sessionId, message, settings) {
    return new Promise(function(resolve, reject) {
      var apiKey, config, i, len, messages, model, msg, options, postData, provider, ref, req, session;
      ({apiKey, provider, model} = settings);
      provider = provider || 'zhipu';
      model = model || 'glm-4-flash';
      config = MODELS[provider];
      if (!config) {
        return reject(new Error(`Unknown provider: ${provider}`));
      }
      session = getSession(sessionId);
      messages = [
        {
          role: 'system',
          content: 'You are CoffeeClaw, a helpful AI assistant. Respond in the same language the user uses. Be friendly and helpful.'
        }
      ];
      if (session.messages) {
        ref = session.messages;
        for (i = 0, len = ref.length; i < len; i++) {
          msg = ref[i];
          messages.push({
            role: msg.role,
            content: msg.content
          });
        }
      }
      messages.push({
        role: 'user',
        content: message
      });
      postData = JSON.stringify({
        model: model,
        messages: messages,
        stream: false
      });
      options = {
        hostname: config.baseUrl,
        port: 443,
        path: config.apiPath,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
          'Content-Length': Buffer.byteLength(postData)
        }
      };
      req = https.request(options, function(res) {
        var data;
        data = '';
        res.on('data', function(chunk) {
          return data += chunk;
        });
        return res.on('end', function() {
          var e, result;
          try {
            result = JSON.parse(data);
            if (result.error) {
              return reject(new Error(result.error.message || 'API error'));
            } else if (result.choices && result.choices[0]) {
              return resolve(result.choices[0].message.content);
            } else {
              return reject(new Error('Unknown response format'));
            }
          } catch (error) {
            e = error;
            return reject(e);
          }
        });
      });
      req.on('error', reject);
      req.setTimeout(60000, function() {
        req.destroy();
        return reject(new Error('Request timeout'));
      });
      req.write(postData);
      return req.end();
    });
  };

  sendToOpenClaw = async function(sessionId, message) {
    var apiKey, response, settings;
    settings = loadSettings();
    apiKey = settings.apiKey;
    if (!apiKey) {
      throw new Error('No API key configured');
    }
    addToSession(sessionId, 'user', message);
    response = (await callAPI(sessionId, message, settings));
    addToSession(sessionId, 'assistant', response);
    return response;
  };

  mainWindow = null;

  createWindow = function() {
    mainWindow = new BrowserWindow({
      width: 900,
      height: 800,
      minWidth: 600,
      minHeight: 600,
      webPreferences: {
        nodeIntegration: false,
        contextIsolation: true,
        preload: path.join(__dirname, 'preload.js')
      }
    });
    mainWindow.loadFile('index.html');
    return mainWindow.on('closed', function() {
      return mainWindow = null;
    });
  };

  app.whenReady().then(function() {
    createWindow();
    return app.on('activate', function() {
      if (BrowserWindow.getAllWindows().length === 0) {
        return createWindow();
      }
    });
  });

  app.on('window-all-closed', function() {
    if (process.platform !== 'darwin') {
      return app.quit();
    }
  });

  ipcMain.handle('send-message', async function(event, sessionId, message) {
    var e, result;
    try {
      result = (await sendToOpenClaw(sessionId, message));
      return result;
    } catch (error) {
      e = error;
      throw e.message || e;
    }
  });

  ipcMain.handle('check-status', async function() {
    var configured, running, settings;
    running = (await checkOpenClawPromise());
    configured = isConfigured();
    settings = loadSettings();
    if (!running && configured) {
      startOpenClaw();
      return {
        running: false,
        starting: true,
        configured: true,
        hasApiKey: !!settings.apiKey
      };
    }
    return {
      running,
      starting: false,
      configured,
      hasApiKey: !!settings.apiKey
    };
  });

  ipcMain.handle('check-prerequisites', async function() {
    return {
      platform: getPlatform(),
      isWindows: isWindows,
      isMac: isMac,
      nodeInstalled: (await checkNodeInstalled()),
      npmInstalled: (await checkNpmInstalled()),
      openclawInstalled: (await checkOpenClawInstalled()),
      wslInstalled: isWindows ? (await checkWSLInstalled()) : false
    };
  });

  ipcMain.handle('create-session', function() {
    return createSession();
  });

  ipcMain.handle('get-session', function(event, sessionId) {
    return getSession(sessionId);
  });

  ipcMain.handle('list-sessions', function() {
    return listSessions();
  });

  ipcMain.handle('delete-session', function(event, sessionId) {
    deleteSession(sessionId);
    return true;
  });

  ipcMain.handle('get-history', function() {
    return listSessions();
  });

  ipcMain.handle('clear-history', function() {
    var key, sessions;
    sessions = loadSessions();
    for (key in sessions) {
      delete sessions[key];
    }
    saveSessions(sessions);
    return true;
  });

  ipcMain.handle('run-setup', async function(event, apiKey) {
    var e, installed, result, started, token;
    result = {
      installing: false,
      configuring: false,
      starting: false
    };
    installed = (await checkOpenClawInstalled());
    if (!installed) {
      result.installing = true;
      try {
        await installOpenClaw();
      } catch (error) {
        e = error;
        throw new Error('Failed to install OpenClaw: ' + e.message);
      }
    }
    result.configuring = true;
    token = createDefaultConfig(apiKey);
    result.starting = true;
    started = (await startOpenClaw());
    if (!started) {
      throw new Error('Failed to start OpenClaw gateway');
    }
    return result;
  });

  ipcMain.handle('get-settings', function() {
    return loadSettings();
  });

  ipcMain.handle('save-settings', function(event, newSettings) {
    var key, settings, value;
    settings = loadSettings();
    for (key in newSettings) {
      value = newSettings[key];
      settings[key] = value;
    }
    saveSettings(settings);
    return true;
  });

  ipcMain.handle('get-models', function() {
    return MODELS;
  });

  ipcMain.handle('save-api-key', function(event, apiKey) {
    var base, config, settings;
    settings = loadSettings();
    settings.apiKey = apiKey;
    saveSettings(settings);
    if (configExists()) {
      config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
      if (config.env == null) {
        config.env = {};
      }
      config.env.ZHIPU_API_KEY = apiKey;
      if (config.models == null) {
        config.models = {};
      }
      if ((base = config.models).providers == null) {
        base.providers = {};
      }
      config.models.providers.glm = {
        baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
        apiKey: apiKey,
        api: 'openai-completions',
        models: [
          {
            id: 'GLM-4-Flash',
            name: 'GLM 4 Flash'
          },
          {
            id: 'GLM-4.5-air',
            name: 'GLM 4.5 air'
          },
          {
            id: 'GLM-4.7',
            name: 'GLM 4.7'
          }
        ]
      };
      fs.writeFileSync(configFile, JSON.stringify(config, null, 2));
      createAgentConfig(apiKey);
    }
    return true;
  });

}).call(this);
