// Generated by CoffeeScript 2.7.0
(function() {
  // CoffeeClaw - Preload Script
  var contextBridge, ipcRenderer;

  ({contextBridge, ipcRenderer} = require('electron'));

  contextBridge.exposeInMainWorld('api', {
    sendMessage: function(sessionId, message) {
      return ipcRenderer.invoke('send-message', sessionId, message);
    },
    checkStatus: function() {
      return ipcRenderer.invoke('check-status');
    },
    checkPrerequisites: function() {
      return ipcRenderer.invoke('check-prerequisites');
    },
    runSetup: function(apiKey) {
      return ipcRenderer.invoke('run-setup', apiKey);
    },
    getSettings: function() {
      return ipcRenderer.invoke('get-settings');
    },
    saveSettings: function(settings) {
      return ipcRenderer.invoke('save-settings', settings);
    },
    saveApiKey: function(apiKey) {
      return ipcRenderer.invoke('save-api-key', apiKey);
    },
    getModels: function() {
      return ipcRenderer.invoke('get-models');
    },
    createSession: function() {
      return ipcRenderer.invoke('create-session');
    },
    getSession: function(sessionId) {
      return ipcRenderer.invoke('get-session', sessionId);
    },
    listSessions: function() {
      return ipcRenderer.invoke('list-sessions');
    },
    deleteSession: function(sessionId) {
      return ipcRenderer.invoke('delete-session', sessionId);
    },
    getHistory: function() {
      return ipcRenderer.invoke('get-history');
    },
    clearHistory: function() {
      return ipcRenderer.invoke('clear-history');
    }
  });

}).call(this);
