// Generated by CoffeeScript 2.7.0
(function() {
  // CoffeeClaw - Preload Script
  var contextBridge, ipcRenderer;

  ({contextBridge, ipcRenderer} = require('electron'));

  contextBridge.exposeInMainWorld('api', {
    sendMessage: function(message) {
      return ipcRenderer.invoke('send-message', message);
    },
    checkStatus: function() {
      return ipcRenderer.invoke('check-status');
    },
    runSetup: function(apiKey) {
      return ipcRenderer.invoke('run-setup', apiKey);
    },
    getSettings: function() {
      return ipcRenderer.invoke('get-settings');
    },
    saveApiKey: function(apiKey) {
      return ipcRenderer.invoke('save-api-key', apiKey);
    },
    getHistory: function() {
      return ipcRenderer.invoke('get-history');
    },
    clearHistory: function() {
      return ipcRenderer.invoke('clear-history');
    }
  });

}).call(this);
