// Generated by CoffeeScript 2.7.0
(function() {
  // CoffeeClaw - Preload Script
  var contextBridge, ipcRenderer;

  ({contextBridge, ipcRenderer} = require('electron'));

  contextBridge.exposeInMainWorld('api', {
    sendMessage: function(sessionId, message) {
      return ipcRenderer.invoke('send-message', sessionId, message);
    },
    checkStatus: function() {
      return ipcRenderer.invoke('check-status');
    },
    checkPrerequisites: function() {
      return ipcRenderer.invoke('check-prerequisites');
    },
    hasBackup: function() {
      return ipcRenderer.invoke('has-backup');
    },
    runSetup: function(apiKey) {
      return ipcRenderer.invoke('run-setup', apiKey);
    },
    getSettings: function() {
      return ipcRenderer.invoke('get-settings');
    },
    saveSettings: function(settings) {
      return ipcRenderer.invoke('save-settings', settings);
    },
    saveApiKey: function(apiKey) {
      return ipcRenderer.invoke('save-api-key', apiKey);
    },
    getModels: function() {
      return ipcRenderer.invoke('get-models');
    },
    createSession: function() {
      return ipcRenderer.invoke('create-session');
    },
    getSession: function(sessionId) {
      return ipcRenderer.invoke('get-session', sessionId);
    },
    listSessions: function() {
      return ipcRenderer.invoke('list-sessions');
    },
    deleteSession: function(sessionId) {
      return ipcRenderer.invoke('delete-session', sessionId);
    },
    getHistory: function() {
      return ipcRenderer.invoke('get-history');
    },
    clearHistory: function() {
      return ipcRenderer.invoke('clear-history');
    },
    getBots: function() {
      return ipcRenderer.invoke('get-bots');
    },
    getBot: function(botId) {
      return ipcRenderer.invoke('get-bot', botId);
    },
    getActiveBot: function() {
      return ipcRenderer.invoke('get-active-bot');
    },
    createBot: function(botConfig) {
      return ipcRenderer.invoke('create-bot', botConfig);
    },
    updateBot: function(botId, updates) {
      return ipcRenderer.invoke('update-bot', botId, updates);
    },
    deleteBot: function(botId) {
      return ipcRenderer.invoke('delete-bot', botId);
    },
    setActiveBot: function(botId) {
      return ipcRenderer.invoke('set-active-bot', botId);
    },
    getBotTemplates: function() {
      return ipcRenderer.invoke('get-bot-templates');
    },
    exportBots: function() {
      return ipcRenderer.invoke('export-bots');
    },
    importBots: function(data) {
      return ipcRenderer.invoke('import-bots', data);
    },
    getFeishuStatus: function() {
      return ipcRenderer.invoke('get-feishu-status');
    },
    syncFeishuToOpenClaw: function() {
      return ipcRenderer.invoke('sync-feishu-to-openclaw');
    },
    approveFeishuPairing: function(code) {
      return ipcRenderer.invoke('approve-feishu-pairing', code);
    },
    getLicense: function() {
      return ipcRenderer.invoke('get-license');
    },
    getLicensePrices: function() {
      return ipcRenderer.invoke('get-license-prices');
    },
    activateLicense: function(plan, paymentInfo) {
      return ipcRenderer.invoke('activate-license', plan, paymentInfo);
    },
    addPayment: function(paymentData) {
      return ipcRenderer.invoke('add-payment', paymentData);
    },
    getGitEmail: function() {
      return ipcRenderer.invoke('get-git-email');
    },
    backupSettings: function() {
      return ipcRenderer.invoke('backup-settings');
    },
    listBackups: function() {
      return ipcRenderer.invoke('list-backups');
    },
    restoreBackup: function(backupName, options) {
      return ipcRenderer.invoke('restore-backup', backupName, options);
    },
    getBackupData: function(backupName) {
      return ipcRenderer.invoke('get-backup-data', backupName);
    },
    exportAllSettings: function() {
      return ipcRenderer.invoke('export-all-settings');
    },
    importAllSettings: function(data, options) {
      return ipcRenderer.invoke('import-all-settings', data, options);
    },
    openExternal: function(url) {
      return ipcRenderer.invoke('open-external', url);
    }
  });

}).call(this);
